### ISSUE TITLE
How easy is it for me to add Notes?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#101]
Picked at random Quartet Menu 30 and because it has Medway Boys III AV bootsector, it won't boot with 4MB of memory. Which is why Medway Boys IV was created by Wizzcat.

From an idiot's point of view, do I put the notes into AL now, or wait for the last import of the STonish DB and then make the change there?

**Comment by nguillaumin** [comment]
No point in adding notes now because it's just a test site and database that will get scraped once we deploy to the real site.

Either check with @Brume-AL if he can add a note on Stonish, otherwise you'll have to wait for the menus to be integrated to the real site.

**Comment by MugUK** [comment]
OK I will keep a note in my spreadsheet (when I finally fix the layout) so that they can go in at a later date.
