### ISSUE TITLE
Icon for no scrolltext?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#103]
I'm going through the Bald Eagle disks and all but one of the menus don't have a scroll text. 

How are we going to support these? Two of them have a Teletype style intro thanking "Group X for this crack" and where the music module came from and that's about it.

Menu750 doesn't have anything at all.

**Comment by MugUK** [comment]
Same with all of the Empire menus. Just a small intro with the contents of the disk and nothing else.

**Comment by nguillaumin** [comment]
Hm, I don't know. To me the absence of the scroll icon is enough...

Alternatives:

![6](https://user-images.githubusercontent.com/762512/108630636-19024f00-7466-11eb-937f-cc0d70c77d44.png)

![7](https://user-images.githubusercontent.com/762512/108630637-199ae580-7466-11eb-8c8d-8e911faa1f4c.png)

Not a big fan though (and the first one is a bit hard to get right with the spacing), it's a bit "noisy". But let me know what you think?

**Comment by MugUK** [comment]
OK, if the icon doesn't appear (and we've explained why elsewhere in the site), then leave it off for those menus without a scroller.

**Comment by stgraveyard** [comment]
Yes, I agree. If there is no text available, just remove the icon.
