### ISSUE TITLE
Any idea how to put this in the right direction (Eddie Menu 5)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#104]
This menu was different in that it scrolled from left-to-right. I thought the text would be stored in the normal way, but it isn't. 

Does anyone know a quick way to reverse all of these words so that they're correct? If I have to retype it all, then I will do so, but I'm sure there's got to be a quicker way of doing it.

EIDDE                            TNESERP OT DUORP SI                     5..REVAS KSID                    LLORCS EHT LLA DAER ESAELP            ZTREH 06/05 ELGGOT OT 0 SSERP       TUOBA STSITRA/SNAICISUM YNA SEREHT FI     !!UOY DEEN I SA EM TCATNOC NEHT          STOHS GNISSAP...ROF 1 SSERP               YFOONS....ROF 2 SSERP               STROPS ERUTUF...ROF 3 SSERP            SKSID EHT ROF NNELG KNAHT I              KCARC EHT ROF YDRIB DNA              AGIMA EHT MORF NEKAT ERUTCIP            NONA SUOMAF EHT YB SI DNA                   OT STEERG LAICEPS                            NNELG                                 D.M KERED                             SDEEL NI DIVAD                               EEL                                    NAYRB                       )SKEEW WEF A NI UOY EES LL'I(      @                SIRHC                    SPUORG GNIWOLLOF EHT OT STEERG ARTXE          )REDRO RALUCITRAP ON NI(                       NOITAMOTUA                           SYOB YAWDEM EHT                          SDROLEMIT EHT                           STAR REWES EHT                            .T.F.O.F                                 9 PRAW                                 NOINU EHT                @                A.C.M                              SRENNUREDALB EHT                         STNACILPER EHT                         )AGIMA( ECROFDICA               NETTOGROF EV'I ESLE ENOYNA DNA        LLORCS DRAWKCAB EHT TRATSER OT EMIT    .................................EYB.........................................5......................................4......................................3......................................2......................................1....................................

**Comment by stsilversurfer** [comment]
https://www.browserling.com/tools/text-reverse

**Comment by MugUK** [comment]
It's a bit better. I just need to re-arrange it now.

....................................1......................................2......................................3......................................4......................................5.........................................BYE................................. TIME TO RESTART THE BACKWARD SCROLL AND ANYONE ELSE I'VE FORGOTTEN ACIDFORCE (AMIGA) THE REPLICANTS THE BLADERUNNERS M.C.A @ THE UNION WARP 9 F.O.F.T. THE SEWER RATS THE TIMELORDS THE MEDWAY BOYS AUTOMATION (IN NO PARTICULAR ORDER) EXTRA GREETS TO THE FOLLOWING GROUPS CHRIS @ (I'LL SEE YOU IN A FEW WEEKS) BRYAN LEE DAVID IN LEEDS DEREK M.D GLENN SPECIAL GREETS TO AND IS BY THE FAMOUS ANON PICTURE TAKEN FROM THE AMIGA AND BIRDY FOR THE CRACK I THANK GLENN FOR THE DISKS PRESS 3 FOR...FUTURE SPORTS PRESS 2 FOR....SNOOFY PRESS 1 FOR...PASSING SHOTS THEN CONTACT ME AS I NEED YOU!! IF THERES ANY MUSICIANS/ARTISTS ABOUT PRESS 0 TO TOGGLE 50/60 HERTZ PLEASE READ ALL THE SCROLL DISK SAVER..5 IS PROUD TO PRESENT EDDIE

**Comment by MugUK** [comment]
One less on the To Do list :)

**Comment by nguillaumin** [comment]
Nice! :+1:
