### ISSUE TITLE
Incorrect filename for Brotherhood of Plebs 7 (one from Brume)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#105]
I've noticed that the .ZIP for Brotherhood of Plebs 7 is named "BOP9.MSA".

There's already a BOP9.MSA inside Brotherhood of Plebs 9 :)

**Comment by Brume-AL** [comment]
Thanks Mike, that's fixed now.

**Comment by MugUK** [comment]
Cheers
