### ISSUE TITLE
Quick Note fix for any instance of Great Courts II

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#107]
Saw this on eBay earlier - https://www.ebay.co.uk/itm/Atari-ST-Game-Software-Manual-Paperwork-Great-Courts-II/124569538244?hash=item1d00ec4ec4:g:AQ8AAOSwz5JgJSsf - and it is a note that was included with the game.

Useful to include with the game information? In all languages too.

**Comment by MugUK** [comment]
![s-l1600](https://user-images.githubusercontent.com/17252699/108912928-34fe2000-7621-11eb-88be-437ab9dd522b.jpg)

**Comment by MugUK** [comment]
I honestly thought I'd uploaded the image last night. Guess not! My apologies.

**Comment by nguillaumin** [comment]
No worries. This type of stuff could go in the "goodies" of a release maybe? You can already upload scans in the Cpanel (for maps, manuals, etc) and they are displayed in the release page in a tile "what's in the box". Alternatively use a "game fact" for it? But in any case I wouldn't think we need something new in the DB to store this.

**Comment by MugUK** [comment]
OK with whatever is going to be easiest. There's not that many games that came bundled with an "OK, we didn't quite think this feature through" :)

**Comment by nguillaumin** [comment]
Is that something you're happy to do yourself via the CPANEL? (Not sure if you're a regular contributor in the DB or not). Otherwise I can add it.

**Comment by nguillaumin** [comment]
I have added it on the site: https://www.atarilegend.com/games/release/1485
