### ISSUE TITLE
Not sure if this is a Stonish error or a DB error

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#108]
A comment on Atari Forum from someone trying to track down a menu they used to have caused a bit of an error on Stonish's search. 

If you type in Jimmy White's ... it fills it up to Jimmy White's Whirlwind Snooker which no-one calls it on any menu. So when you search for it, you get no results.

The only way around it was to search for "Snooker" and then wade through all of the other titles too.

Is this just down to Brume's search engine, or will we have to implement a better search for these long-winded titles to include an "also known as" option?

**Comment by nguillaumin** [comment]
Funny, I was following that post too, and I'm pretty sure I came across the menu they're looking for, but I can't find it anymore now...

I think it's a Stonish bug, probably with the quote `'`. If you search on AL, it works. AL also support "also known as", for example you can search "Cruise for a Corpse" or "Croisière pour un cadavre".

So I think we're good here! :smile:
