### ISSUE TITLE
ADR Menu 000 Disk B is corrupted Brume

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#110]
I was copying it to my Steem partition so that I could play around with the Demo Construction Kit that is on it. Disks A & C work OK, but Disk B has a lot of errors on the folders on the disk.

**Comment by Brume-AL** [comment]
I can't see any bug with this menu on Stonish nor Atari Legend. Maybe something went wrong when I uploaded the big archive?
Can you confirm it's on your side with the zip available on the site?
Thanks in advance.

**Comment by MugUK** [comment]
The ZIP is from your STonish archive (the 2.2Gb one). I can't copy any of the files from the image to my STeem emulated drive C: - the other two disks work OK. I'll download it again tomorrow on my laptop and have another go.

**Comment by MugUK** [comment]
![2021-03-02](https://user-images.githubusercontent.com/17252699/109628443-a87cc180-7b3a-11eb-89fa-c68260ce6d14.png)

Tried again with a fresh copy of the disk image from Stonish.net Brume, and I get the same result.

**Comment by nguillaumin** [comment]
I checked the version I have which comes from TOSEC in `.st` format, and unfortunately it is corrupted as well... So not sure what we can do here unless we find another source?

**Comment by MugUK** [comment]
I've downloaded a few versions of DCK (mostly French) but as it's the 2nd disk that's corrupt, hopefully the files won't have changed much between the English & French versions.

**Comment by Brume-AL** [comment]
Didn't find the time to repair it, sorry. Will do it asap, it should be easy to fix.

**Comment by nguillaumin** [comment]
How would do you repair it out of curiosity? Just get a good copy of DCK and copy the files over, since they're just data files? If yes it's something I could do.

**Comment by MugUK** [comment]
In theory, yes. Get a different Disk 2 and make a directory listing of the corrupt one (if it allows it) and a directory listing of the replacement. 

If they both match, then:

a) a new disk image will need to be created - using the same disk parameters and disk label of the Adrenalin disk
b) Then copy the files across from the different disk to the new disk.
c) Upload the new disk. I think the Adrenalin one has a bootsector on it? 

That should fix it.

**Comment by nguillaumin** [comment]
Ok makes sense. Believe it or not I did buy DCK at the time and we had "demomaking" contests with my friends at school 🤣 My original are long lost unfortunately.

Any tips about the boot sector? How to extract it from the source disk and write back to the new disk?

**Comment by MugUK** [comment]
I used to extract them, convert it to source code using Easy Rider and then make a new installer for it.  Not that I stole other people's work for use with Super / Professional Virus Killer :)

**Comment by nguillaumin** [comment]
So, here's what I've done:
- Tried this version: http://www.pouet.net/prod.php?which=13382 The file list did not exactly match, so I presume it's a slightly different version (US one perhaps)?
- Found that one: https://www.planetemu.net/rom/atari-st-applications-st/demo-construction-kit-1992-eurosoft-fr-disk-2-of-3-2 . The file list is identical on that one, including the file dates
- However the boot sector on this one did not run (straight to desktop). So I copied the boot sector from the AL image (first 512 sectors with `dd` on Linux)
- Finally repaired image is here: [ADR00B_REPAIRED.zip](https://github.com/atari-legend/atari-legend/files/6371664/ADR00B_REPAIRED.zip)

Let me know what you think, if it's ok with everyone I will upload it to AL to replace the damaged one.

Here's the bootsector diff (original is on the left, the dump from PlaneteEmu is on the right):

![diff](https://user-images.githubusercontent.com/762512/115988582-b9860400-a5ba-11eb-859f-f38db27d893b.png)

**Comment by MugUK** [comment]
The last two bytes are a checksum to ensure that the disk bootsector will be a bootable one. Because the bytes in a few sections are slightly different, this causes the checksums to not match.  The main thing is that the files all match, the bootsector is a bonus :)

Nice work Nico!

**Comment by Brume-AL** [comment]
Thanks for your effort Nico 👍

Unfortunately, in that case, repairing the disk isn't so easy. Some stuffs have been added/modified on ADR #0B compared to the version that's available on Planetemu.
For instance, the size of the directory 'DESSIN' doesn't match with your repaired disk.
On the left the original ADR #0B. On the right, the repaired version:
![ADR00B_00001](https://user-images.githubusercontent.com/12120244/115989324-1800b180-a5be-11eb-88c5-8a933c33a95c.png)

Same for the font directory:
![ADR00B_00002](https://user-images.githubusercontent.com/12120244/115989349-2c44ae80-a5be-11eb-82c6-dace3f6a38fe.png)

**Comment by nguillaumin** [comment]
Dang you're right! However there is another version on PlaneteEmu that matches the file list: https://www.planetemu.net/rom/atari-st-applications-st/demo-construction-kit-1992-eurosoft-fr-disk-2-of-3-a . However copying the boot sector across did not work (results in corrupted file structure). So I did take my "bad" repair and copy files across.

Here's the new version, I hope good this time...

[ADR00B_REPAIRED.zip](https://github.com/atari-legend/atari-legend/files/6371758/ADR00B_REPAIRED.zip)

**Comment by nguillaumin** [comment]
I have replaced the disk on AL with my repaired copy.
