### ISSUE TITLE
Menus: CPANEL

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#111]
Todo list for me to complete in the CPANEL regarding the menus:

- [x] Upload and managing of dumps
- [x] Populate the DB changelog 
- [x] Ability to set / edit a menu condition
- [x] Ability to set / edit who donated the menu
- [ ] Nicer (drag'n drop?) re-ordering of menus
- [x] Check that releases can be properly deleted even if they have attributes (trainers, incompatibility, ...)
- [x] Pagination for large tables
- [x] Auto-complete to select games, software (rather than big dropdowns)

**Comment by stgraveyard** [comment]
Nico, regarding cpanel, are you know making the 'white cpanel' I have seen pop up or will this be integrated in the existing cpanel. What is the plan for the cpanel?

**Comment by nguillaumin** [comment]
I am building a separate CPANEL, using the same tools (Laravel, Bootstrap). All the menus administration is done in the new CPANEL, but the legacy CPANEL is still used for everything else (it's too much work to migrate everything, I hope it will happen over time as we add new functions and migrate parts from the old to the new).

The new CPANEL is available under `/admin`, I also added a link in the dropdown menu:

![1](https://user-images.githubusercontent.com/762512/111914468-59a7b500-8a72-11eb-8e42-70409c1c6195.png)

I also tried to provide cross edit links to the right CPANEL to make things easier:

![2](https://user-images.githubusercontent.com/762512/111914549-bc994c00-8a72-11eb-802c-0a26ad6e8f53.png)

It is currently in a white scheme, yes. I'm not set on the look and feel, it's something we can easily change later. But we do need screens to administer the menus (for example for Brume to make corrections or add new menus, or Mug-UK to add scrolltexts) before we can fully go live with the menus.

**Comment by stgraveyard** [comment]
Thank you for the info. I will check this out this week after my video is finished. First thing that comes to mind. If we ever go live with 2 different cpanels, in the intermediate fase, we have to make sure it is not confusing to the db admins, or mistakes will be made. Just a thought...

More in this in a few days...

**Comment by stgraveyard** [comment]
This is amazing. Very nice and clean.

**Comment by nguillaumin** [comment]
I didn't get to do the "fancy" drag'n drop re-reordering of menus. I probably won't at this stage so closing this, however for future reference here's the library I intended to use: http://sortablejs.github.io/Sortable/

**Comment by stgraveyard** [comment]
Yeah, that is cool :-)
