### ISSUE TITLE
BUG - Reviews - CPANEL

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#112]
Hi Nico,

I found a little bug in the review section of the cpanel. 

When using the release year feature like this : 

![image](https://user-images.githubusercontent.com/4339294/111905628-e5a6e600-8a4c-11eb-94c1-f60730807014.png)

When checking the preview we see this  : 

![image](https://user-images.githubusercontent.com/4339294/111905652-02431e00-8a4d-11eb-9576-f08456ae949c.png)

This could also be wrong in the article and interview section, and I haven't seen it on the main site as this review is still in draft mode, release is planned next weekend. 

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Should be fixed now.

**Comment by stgraveyard** [comment]
perfect!
