### ISSUE TITLE
BitDefender really doesn't like AL's legacy site

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#113]
Maarten asked me to review the Krall Brothers interview (which is done) and all the time whilst doing this, BitDefender kept telling me that I've been "protected" from whatever AL's site was doing. 

Maarten suggested I get them uploaded here so some investigation could be done by Nico  :)

![2021-03-27 (2)](https://user-images.githubusercontent.com/17252699/112716615-4ae05880-8edf-11eb-9ae5-8b5a1a46b3b4.png)

![2021-03-27](https://user-images.githubusercontent.com/17252699/112716627-5895de00-8edf-11eb-8b9a-237e1d22b1ae.png)

![2021-03-27 (1)](https://user-images.githubusercontent.com/17252699/112716631-5e8bbf00-8edf-11eb-9408-5ef2d3569f4e.png)

It seems like I have to add the AL site to my exceptions list if I want to get rid of the 70+ warnings re-occurring.

**Comment by nguillaumin** [comment]
Honestly, I have no idea. There's no dodgy script or anything on the site, as you can imagine. I even removed Google Analytics in favor of installing our own analytics system (Matomo) to avoid 3rd party tracking. I did run a few online security scans and they did not found anything.

The messages are not very detailed either so it's hard to troubleshoot. Is there any more details? "Access your files from an external source" does not even make sense as it's not really possible from a website.

It looks like a false positive to me, perhaps the AL IP address ended up in one of the BitDefender "bad" list for some reason..

**Comment by nguillaumin** [comment]
Wait, you said Legacy site, right? The screenshot showed the new site... Can you confirm?

If it's the legacy site, it does have a lot of scripts, none of them dodgy or anything, but it's much more of a "mess" that could trigger such warnings, even if they're probably just false positive as well. Not sure what we can do in practice, without more details of what BitDefender thinks the problem is...

**Comment by MugUK** [comment]
It was whatever link Maarten sent me to review the interview .. hang on, I'll copy & paste it below.

https://legacy.atarilegend.com/admin/interviews/interviews_edit.php?interview_id=48

**Comment by MugUK** [comment]
More than likely a false positive. I've added the main URL to BitDefender's Exceptions list.
