### ISSUE TITLE
Importing the scrolltexts - process query

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#114]
Just so I know the process as I've done a load of them, but not sure if I'm supposed to be putting them directly into AL (and Demozoo), or if Brume puts them into STonish first and then they are imported by Nico.

**Comment by nguillaumin** [comment]
Either we put them in Stonish and they get importer, or alternatively we wait for the menus to be made live on AL, and you can put them directly in AL via CPANEL. Maybe the latter is more practical, if Brume does not have time to add them on Stonish.

**Comment by MugUK** [comment]
Happy to go with whichever so long as they don't get zapped. If I'm waiting for the menus to go live, then I can crack on and do a lot more of them.

They're in a folder on my Dropbox (split into no text / with text folders).

**Comment by MugUK** [comment]
I've not finished (by a long way) but I did a lot more whilst I was at my other half's. She doesn't get up too early in the morning, so plenty of time to get extra scrolltexts extracted :)

**Comment by nguillaumin** [comment]
Now that it's live, you can finally contribute these! You can navigate to the menu of your choice on the main site and click the Edit icon:

![1](https://user-images.githubusercontent.com/762512/114311685-057f7600-9af0-11eb-8fec-0882df30e4a9.png)

Then just fill in the Scrolltext field and save:

![2](https://user-images.githubusercontent.com/762512/114311709-19c37300-9af0-11eb-90fd-4005d72c3b40.png)

Or you can also go via the new CPANEL link:

![3](https://user-images.githubusercontent.com/762512/114311749-3fe91300-9af0-11eb-9ded-dbf51a5a7429.png)

Then go on the left Menus > Sets:

![4](https://user-images.githubusercontent.com/762512/114311772-5b541e00-9af0-11eb-9907-2c2e82f588ed.png)

Then drill down into the set you want, then the menu, then the disk.

Hope this is clear, let me know if not! I'm open to feedback on the new CPANEL too.

**Comment by MugUK** [comment]
I've used both ways to add scrolltexts now. Many thanks for the new feature.

I have requested a few tweaks to it though :)

**Comment by MugUK** [comment]
If someone wants to try out the scrolltexts for a single group, then all of Adrenalin UK disks (normal and PD ones) have all been uploaded. There's also a lot of dates for the menu releases too as they were nice enough to put them into the scrolltexts and/or on screen.

**Comment by nguillaumin** [comment]
Very, very cool! And to have the dates is the cherry on top :cherries: Thanks!
