### ISSUE TITLE
MAIN SITE - Game facts not displayed nice

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#115]
Nico, 

This is a quicky for when you are working on the game detail page if it is an easy fix (I don't know). 

I have added some nice trivia on the game page of Son SHu Shi. So a fact is added using cpanel : 

CPANEL 

![image](https://user-images.githubusercontent.com/4339294/112724295-f8209400-8f12-11eb-9b52-d411efad9385.png)

MAIN SITE

![image](https://user-images.githubusercontent.com/4339294/112724323-0d95be00-8f13-11eb-980e-1341fd58db91.png)

Now I know this is a lot of text and I know the tile is small, but would it be possible to add a quick fix so at least we have the 'enters' in there? I know I should have done this when I made it. Sloppy work by me.

It is not urgent, but maybe a nice one when you are workin on the page.

Thanks a lot.

Maarten

**Comment by nguillaumin** [comment]
No problem, it was a bug the new lines should have been correctly rendered.

**Comment by stgraveyard** [comment]
Perfect!
