### ISSUE TITLE
Display latest ALTV videos

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#116]
I've been looking at fetching the last 3 ALTV videos from YouTube and display them on the home page. It looks like this currently:

![1](https://user-images.githubusercontent.com/762512/114277931-a22d0f80-9a2d-11eb-9bbf-bb57ad3630fd.png)

Or alternatively:

![2](https://user-images.githubusercontent.com/762512/114278081-4adb6f00-9a2e-11eb-9501-0ab4a18374a2.png)

@stgraveyard Let me know what you think, or if you have better ideas for presentation?

**Comment by stgraveyard** [comment]
I love the first one! So this will replace the AL TV tile we have now? 
Could we also add 'social corner' to the right colom in full view? Or too much trouble?

**Comment by MugUK** [comment]
Nice one.

**Comment by nguillaumin** [comment]
Okay, with a few more tweaks:

![3](https://user-images.githubusercontent.com/762512/114284881-45445000-9a53-11eb-8d96-65062278c9d6.png)

**Comment by stgraveyard** [comment]
Super nice! Cool addition to the new menu section tomorrow! It will be such a kick ass release! thank you.

**Comment by nguillaumin** [comment]
This is now deployed.

**Comment by stgraveyard** [comment]
Nico, 

I love it. 

1 remark, probably not new but something that slipped under my radar. Main page, going to phone view  : 

![image](https://user-images.githubusercontent.com/4339294/114305231-75cdcd80-9ad7-11eb-8256-dc4d6e487401.png)

There are 2 columns in 1 column mode. I guess this is the nature of the template? 

I can live with it.

Maarten

**Comment by nguillaumin** [comment]
Not sure if it was a pre-existing bug or not, but I think I fixed it now.

**Comment by stgraveyard** [comment]
Yes you did! Awesome.
