### ISSUE TITLE
GAME DETAIL PAGE - Youtube tile

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#117]
Nico,

I was thinking, now that you have found a way to add youtube link. 
It would be cool if we can add youtube links to games. What I would like is, when we store a link to a certain game, a tile would apear on this game detail page with the youtube video. If a  game has more than one link, it would randomly add one link in the tile (with screenshot and info) and below the info, list the other links as hyperlink text. 

I would like to be able to : 
Add a youtube link
Add a categorie (review video, let's play video ...) 

When I make videos, I also record gameplay footage. I is a small step for me to also make let's play videos of the games I use in the main videos, and upload these. I think the AL werbsite could greatly be enhanced with this feature.

Something to discuss.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I actually thought of something similar, but that would be more automated: We could run a search on YouTube for videos with a name like `Atari ST <game name>` or `Atari ST <game name> long play`, and embed the 3 first results or something. The drawback is that it may not work 100% and we can't control the quality of the video, but it means we could display videos for a lot of games without having to record them ourselves :wink: 

What do you think? We could also do both, they're not mutually exclusive.

**Comment by stgraveyard** [comment]
No, I think we could get in trouble this way. Also, there is a lot of shit on youtube...I don't think it is safe.

**Comment by stgraveyard** [comment]
I also don't want AL to become some kind of news portal. It gives me that feeling when we do this. Only original content as far as I'm concerned.

**Comment by stgraveyard** [comment]
On the other hand, it might lure more people into visiting AL. But than again, a simple search on youtube can do the trick for these kind of videos ...

I don't know Nico. I like the idea of exclusive content ...

**Comment by nguillaumin** [comment]
I had a prototype going that was running searches on the YouTube API:

![1](https://user-images.githubusercontent.com/762512/116007971-a56df100-a612-11eb-876c-4b8c7c9f428d.png)

Unfortunately the quotas are way too low, we're only permitted 100 searches / day which I would not be enough... So it will have to be a manual addition of selected YouTube videos for each game.

**Comment by stgraveyard** [comment]
Hi Nico, 

I have a really hard time with this one. Maybe I am wrong here, but adding a bunch of random YT videos gives everything a very cheap newportal feeling to me. IMO, we have social media for these kinds of things. Maybe I need to grow mentally, but for now, I don't like it. I want to be able to add YT videos, but I want to add AL YT videos. Original AL content, not random YT crap. 
I personally would add let's play videos of wasabim or ataricrypt, but that is about it...

Maarten

**Comment by nguillaumin** [comment]
Then all is well because we cannot do the "portal" approach due to the limitations of the YouTube API as per my previous comment. Videos will be added manually in CPANEL.

**Comment by stgraveyard** [comment]
I really like that idea. Thanks.

**Comment by stgraveyard** [comment]
So Nico, how about this one? I would love to see it in Dev for testing ;-)

**Comment by nguillaumin** [comment]
Well I did not implement your version, only the test I did by fetching videos from the YouTube API. One issue is that I did not want to change the old CPANEL to allow associating YouTube videos, and in the new CPANEL we did not have any screens to edit games yet.

However now we have these screens, as I created them to edit the music of each game (and I have expanded since to edit the credits and the screenshots). So I just added another section to associate YouTube videos. It's deployed on dev if you want to check, I did a test on "Droid - Special Edition": https://dev.atarilegend.com/games/6451 &  https://dev.atarilegend.com/admin/games/games/6451/videos

I kept it very basic, you can juste paste a YouTube link in CPANEL and that's it. Unfortunately I cannot easily retrieve the video title or anything else, so on the game page it just displays the video as-is.

**Comment by stgraveyard** [comment]
I really like this Nico, but damn ... I do miss the title and (part of) the description, that would have been the cherry on the cake. Also that it play's within the AL site is really nice!

**Comment by nguillaumin** [comment]
On the front page I'm using a [RSS feed](https://www.youtube.com/feeds/videos.xml?channel_id=UCN7ePamELHkBVAHwXa4cubg) that retrieves the last N videos, with all the metadata. On the game page I'm just embedding the video that is added in CPANEL, via an iframe. There's no built-in way to retrieve more details.

I may have a solution though, YouTube supports "oEmbed" which is a simple way to retrieve information about something (a video in that case) for embedding purposes: https://youtube-eng.googleblog.com/2009/10/oembed-support_9.html . So I should be able to get some details (title at least) when the video is added in CPANEL. I'll have a look.

**Comment by nguillaumin** [comment]
I have updated DEV with a new version that fetches the author and title of the video. Unfortunately I can't get more than that easily. Have a look?

(FYI I had to reset the DEV database so if you had added videos to some games they got removed).

**Comment by stgraveyard** [comment]
Just perfect. This can go to PROD for me. Thank you very much.

**Comment by nguillaumin** [comment]
Thanks, this is now deployed to prod!

**Comment by stgraveyard** [comment]
You're the best!

**Comment by nguillaumin** [comment]
I have tried to associate all the AL videos with the relevant games. It does spice up a bit the game pages, it's cool :smile:

**Comment by stgraveyard** [comment]
Nico, may I ask one more thing. Wouldn't it be better to have the video tile on the left side for a better balance? 
Check out the Droid, Droid2 and Hoog pages and let me know what you think.
I think it would be better, even if there are no interviews (as with most games)...

**Comment by nguillaumin** [comment]
We could, but then it would appear first on mobile (the first column shows, then the central one, then the right). This is partly why it's a bit unbalanced, so that the first column does not push down the screenshots too much. But I can do it if you want?

**Comment by stgraveyard** [comment]
I think yes. I do think screenshots should come first on phone, but there are so little games with a youtube video and in other resolutions I think it brings more balance. And the videos are getting better, so why not give it a shot ;)

**Comment by nguillaumin** [comment]
Ok so what I did is that I put the videos on the left, but only if there are no boxscans, otherwise it stays on the right, so that we hopefully get the best of both worlds :smile:

**Comment by stgraveyard** [comment]
Bloody perfect! Thanks a lot.
