### ISSUE TITLE
Interviews -  column issue

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#118]
Hi Nico,

This is something Bruno mentioned last week and is something we know how to solve now. This is an interview : 

![image](https://user-images.githubusercontent.com/4339294/114308344-cfd49000-9ae3-11eb-8a7c-d97172305824.png)

Notice where the name of the person is. All good. 

Now let's go to  1 or 2 column : 

![image](https://user-images.githubusercontent.com/4339294/114308371-f1ce1280-9ae3-11eb-9214-f4504605960f.png)

The name box is now below the interview. 

2 possible solutions : 
- put name where we now have 'interview' and add 'intro' where we now have name
- When going to 1 or 2 columns, put name where we have 'interview' and add intro where we have name

What do you think?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I have used the same technique we used on the game page, just swapping the tiles title depending on the screen size.

**Comment by stgraveyard** [comment]
Thank you. Good Job.
Nico this has gone straight to prod. Perfect. But do we still have a dev test server/link?
Sorry I forgot...

**Comment by nguillaumin** [comment]
Yes: https://dev.atarilegend.com/ . Everything goes through there (but sometimes I deploy to prod at the same time, for small changes like this one)
