### ISSUE TITLE
Menu sets - Fix crews

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#119]
When I imported the Stonish menus I used the name of the set as the name of the crew in the AL DB. It means for example that we have a crew named "Pompey Pirates" and one named "Pompey Pirates Krappy Kompact", or one named "Cynix" and "Cynix Codemasters Cartoon Collection", "Cynix Dizzy's Excellent Adventures", etc.

Similarly Stonish did not support having multiple crews for one set but AL does. I'm not familiar with all the menu sets so I don't know if we have the need for that, but for example: are `Arakis / Zuul` two separate crews collaborating on a singe menu set? Currently in the AL DB it has been imported as a single crew named `Arakis / Zuul`.

So these will need to be manually corrected on AL via the new CPANEL, so that the names can be properly displayed. I have fixed "Pompey Pirates Krappy Kompact" as an example:

![5](https://user-images.githubusercontent.com/762512/114312972-f3540680-9af4-11eb-8b44-7aa205d2fe90.png)

If 2 crews were collaborating, it would show `by: Arakis, Zuul`.

The "bad" crews should also be deleted from the DB via the legacy CPANEL (Crew edition is still done in the old CPANEL) - However I just saw that the old CPANEL crew editor does not completely work... I'll have a look at fixing it.

FYI @Brume-AL @stgraveyard

**Comment by Brume-AL** [comment]
I'm just coming to clean up the DB of crew/menus set.
Each set of menus is now attached to the right crew. Have also removed the "bad" crews. I hope I didn't leave some bad names in the DB, I'll take a look carefullt tonight.

**Comment by nguillaumin** [comment]
Thanks a lot, awesome! I did quickly fix the legacy CPANEL to allow crew deletion yesterday, however it's still not working very well (no way to search for example). I think I'll just re-implement the crew editor in the new CPANEL that will be actually quicker. I will create a separate issue for it.
