### ISSUE TITLE
Name of download file of menus

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#122]
Hey @nguillaumin @Brume-AL 

Got this comment on facebook from a fan : 

![image](https://user-images.githubusercontent.com/4339294/114319098-4edfbd80-9b10-11eb-9e01-54847ac66fc2.png)

Is there something we can do?

Cheers,
Maarten

**Comment by stgraveyard** [comment]
Maybe an option so people can choose between a number of an actual name?

**Comment by nguillaumin** [comment]
I'm not sure what they mean? The file should be downloaded with the proper name:

![6](https://user-images.githubusercontent.com/762512/114319478-fe695f80-9b11-11eb-9f04-0b405b0b1e32.png)

We actually had this issue early on but I fixed it: #91 .

Do you know what they mean exactly? Or is it about the file that is inside the ZIP (which I took as-is from Stonish without renaming)?

**Comment by Brume-AL** [comment]
I guess he refers to the name of the file that's temporarily displayed in the browser. He probably didn't see the menu is renamed on the fly.

![Download menu](https://user-images.githubusercontent.com/12120244/114320031-586b2480-9b14-11eb-8ef2-0a7541121306.jpg)

**Comment by MugUK** [comment]
Ask him for a screenshot of the menu he wants to download llike you've done above Maarten and then a screenshot of the file on disk.

**Comment by stgraveyard** [comment]
I have answered him on facebook.

**Comment by MugUK** [comment]
Can this be closed now @stgraveyard ?

**Comment by stgraveyard** [comment]
The never answered, always the same sh*t with these fast click social media people ... Close the damn thing ...

**Comment by MugUK** [comment]
Idiots will always be idiots :)

**Comment by MugUK** [comment]
I think only you or Nico can close this log though.
