### ISSUE TITLE
Date entry on new CPanel - needs to be complete before it's accepted

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#123]
I'm just putting in some dates for Adrenalin PD disks and I notice that if the scrolltext says "June 93", I can't put dd/06/1993 as it won't accept that and the date field changes back to dd/mm/yyyy when I click Save.

So I have to put 01/06/1993 - which is probably the wrong day, but it's the only workaround I can see.

**Comment by nguillaumin** [comment]
This is somewhat expected. It's a date field in the database so it needs all components (day - month - year). I think using 01 is an acceptable compromise. If we wanted something more fine-grained we would need a field for each in the DB, which makes everything else a bit more complicated.

So I would keep it like that for now, unless there's a strong objection.
