### ISSUE TITLE
Menus that contains docs aren't displayed in the list of a game details page

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#124]
When a doc of a game is listed on a menu, the menu isn't listed in the game details page.

See Maupiti Island for instance. The doc are on Supremacy doc CD #2:
https://www.atarilegend.com/menusets/206?page=1#menudisk-4680

But this menu isn't listed on Maupiti Island page:
https://www.atarilegend.com/games/3323

![maupiti Island](https://user-images.githubusercontent.com/12120244/114398637-4e8f0300-9ba0-11eb-9dcb-240ab2abad23.jpg)

**Comment by nguillaumin** [comment]
You're right! It's because initially I did create a release for these menus as well so they would show up, but I changed the DB structure later and there's no more release now, but I did not realize I would have to update the code to find these menus as well... Will fix ASAP! Thanks for noticing.

**Comment by nguillaumin** [comment]
Should be fixed now.

**Comment by Brume-AL** [comment]
That was fast, thank you Nicolas 👍👍
It works like a charm now.
