### ISSUE TITLE
CPANEL - Improve menuset navigation

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#125]
When I'm doing bulk uploads of scrolltexts and I finish with one crew's set and move onto the next, I have to click on 'Cancel'.

I'm then taken back to the very first page of menus, even if I was on page 3.

Can I either have:

a) The ability to double-click on a crew in the main list and then jump to that crew's page. Instead of having to click cancel to go back to the main list.

b) Or an A-Z above the main crew list page, so that I can easily jump to the page which has the same first letter?

**Comment by nguillaumin** [comment]
For A) I think you can use the breadcrumbs at the top:

![1](https://user-images.githubusercontent.com/762512/114433170-ca4d7780-9bc1-11eb-9ad9-dfcb98b9723a.png)

Clicking on "Sets" will return you to the list of sets. However it will not indeed preserve the page you were on before.

I'll see what I can do for an A-Z listing, it's a good idea.

**Comment by MugUK** [comment]
I'd prefer B because I'm moving through my first batch of scrolltext rips (mostly single or small release crews). If you can implement that, it'd be a massive improvement as I go back through and find the larger group scrolltexts.

**Comment by nguillaumin** [comment]
I have implemented the A-Z index, it will be deployed in a few minutes. Let me know what you think?

**Comment by MugUK** [comment]
Woo-hoo - much nicer and easier for me to jump betwen crews that don't have the same first letter :)
