### ISSUE TITLE
Issue with interview - need help urgently

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#128]
HI Nico, 

I'm adding a new interview with Orion which I like to release tomorrow : https://legacy.atarilegend.com/admin/interviews/interviews_edit.php?interview_id=49

But as you can see in the preview, as of question 30, the HTML is not translated correctly. I don't see the issue. Do you? 

Thanks,
Maarten

**Comment by nguillaumin** [comment]
The preview code is poorly written and does a loop over the content (which is not really necessary), but the loop is hard-coded to 30 iterations... I think it will be fine when it's published, because it's just the preview code in the legacy CPANEL. Nonetheless I will make an ugly fix just by doubling the number to 60.

**Comment by stgraveyard** [comment]
Yes I just noticed : 

 for (i = 0; i < 30; i++) {
        var hotspotUrl = '[hotspotUrl=#';
        var hotspotUrl_output = hotspotUrl.concat(i);
        var hotspotUrl_final = hotspotUrl_output.concat(']');
        var nameUrl = '<a href=#';
        var nameUrl_output = nameUrl.concat(i);
        var nameUrl_final = nameUrl_output.concat(' class=standard_tile_link_black>');
        text = text.replaceAll(hotspotUrl_final, nameUrl_final);
        var hotspot = '[hotspot=';
        var hotspot_output = hotspot.concat(i);
        var hotspot_final = hotspot_output.concat(']');
        var name = '<a name=';
        var name_output = name.concat(i);
        var name_final = name_output.concat('>');
        text = text.replaceAll(hotspot_final, name_final);
    }

This was poorly written by yours truly ;) code dating back to 2004 and recycled in 2017 *blush*

**Comment by nguillaumin** [comment]
Ahah :wink: No problem, I have pushed a fix that should be deployed in a few minutes.

**Comment by stgraveyard** [comment]
Not working yet ...

**Comment by nguillaumin** [comment]
It does for me? Maybe clear your cache?

**Comment by stgraveyard** [comment]
ugh, I'm such a NOOB. Thanks Nico. As always, you are the best! 
I will release this gigantic interview tomorrow.
