### ISSUE TITLE
Photo of individual missing

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#130]
Hi Nico,

I think a bug must have crawl in the code, as the photo of the individual in the interview section is now gone : 

![image](https://user-images.githubusercontent.com/4339294/114733986-1b857480-9d44-11eb-88c9-8cae76db8c66.png)

I think this happened in the change you made for the name to be added above the actual interview in 1 column mode?

Thanks,
Maarten

**Comment by nguillaumin** [comment]
This was actually never implemented, I missed it when I rebuilt the site. I pushed a fix which should be deployed in a few minutes

**Comment by stgraveyard** [comment]
I missed this myself. Good job, thanks for the quick fix!
