### ISSUE TITLE
Should we open the download to everyone (no need to register anymore)?

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#133]
(Well, that's not an issue. Sorry, I didn't know where to put it. Feel free to move this topic if needed.)

Since we open Atari Legend around 2004, we always requested people to be registered in order to download games. This is something we seriously have to debate: what's the advantage for us to force people to register on the site nowadays?
Take a look at what is happening on other sites such as Atarimania, Planetemu.net... There's no need to register to download games.

Also considering all menus are downloadable with an incremental number, we can't argue this is a way to protect the site from leeching.
You can download all menus w/o registering:
https://www.atarilegend.com/storage/zips/menus/1.zip
https://www.atarilegend.com/storage/zips/menus/2.zip
https://www.atarilegend.com/storage/zips/menus/3.zip
So a very small script could download all menus even if the downloader has no account on the site.

Let's discuss about this point. Thanks in advance my friend, I'm very curious to know your point of view. 🙂

**Comment by stgraveyard** [comment]
I would say, open downloads, registering only if people want to write reviews or report bugs? 
I don't really know, but for downloads, definitely open it up.

**Comment by nguillaumin** [comment]
Yes, I agree as well. I will have a look.

For the IDs, I did wonder if we should protect against that (leeching scripts)? But I guess if we open up the downloads then it doesn't matter anymore.

**Comment by MugUK** [comment]
When AL was opened, I guess the limits were also there to prevent leeching via whatever multi-downloading tools were available. And hosting / downloads / bandwidth probably cost a lot more? Open up the downloads, but yes, keep it closed shop for those who want to write reviews and comments.

**Comment by nguillaumin** [comment]
Done, downloads of menu and game dumps is now public!
