### ISSUE TITLE
Menus aren't displayed in alphabetical order

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#136]
Have added a new set of menus this morning (Teddystacker).

It's displayed at the end of the list here:
https://www.atarilegend.com/menusets

Thanks in advance for the fix 🙂

**Comment by nguillaumin** [comment]
Ah, sorry. The menu sets list was not sorted and it worked by chance because I imported them in alphabetical order from Stonish. I pushed a fix, should be deployed in a few minutes.
