### ISSUE TITLE
The donator of a menu is deleted

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#137]
When we edit a menu, the donator (which was previously added to the menu) is often deleted.

As an example, try to edit a menu and change its condition. the donator will be removed as soon as you save it. Same result when you add a screenshot, dump, etc.

![Annotation 2021-04-25 111423](https://user-images.githubusercontent.com/12120244/115987913-6fe7ea00-a5b7-11eb-93b2-27166a74a20e.png)
 
Thanks in advance for the fix 😉

**Comment by nguillaumin** [comment]
Thanks, should be fixed now!

Keep the bug reports coming, I test as best I can but I'm not using the CPANEL as much as you guys so I will be missing some issues... Same if you see possible improvements to make your work easier!
