### ISSUE TITLE
Better Individual formatting

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#138]
I was editing Maarten's interview with Jonathan re: Lotus. I noticed that we hadn't linked to Paul Woakes nor Mike Singleton. So I added extra information to Mike's 'Individual' entry and then wondered where I would find it.

Maarten explained how to find it and, it needs some better formattting.

![FireShot Capture 077 - Midwinter - Atari ST game - Atari Legend - www atarilegend com](https://user-images.githubusercontent.com/17252699/115989569-ecc69400-a5b6-11eb-9860-63202802fe9f.png)

I've put extra lines between the list of his games (which I now know is pointless as clicking on the name takes you to the same information) and then two carriage returns and then the Wikipedia entry. It looks a bit of a mess without the carriage returns.

If we know a famous coder has passed away, do we have an option to include a cross symbol as DemoZoo does? Or should we use that in the Individual db entry?

**Comment by nguillaumin** [comment]
Thanks, I have pushed a fix for the formatting, should be up in a few minutes.

Currently we don't handle birth date / death date in the DB, so no option to put a cross. Not opposed to it, but we would have to decide what we want to store (the actual dates, or just a flag "passed away"?) and you guys must be prepared to update the DB with that info :wink: 

Maybe discuss it with the team, and if you want it open a new issue?
