### ISSUE TITLE
Future of demos in the AL DB?

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#139]
Hi @stgraveyard @Brume-AL @MugUK , while working on the crew editor I noticed that we have data in the DB about demos. There's 222 demos in there and 900+ screenshots.

What's the plan with this? In the legacy CPANEL the demo editing screens were not implemented yet. Do we want to keep all of this? Or is it redundant with DemoZoo and we should not be cataloguing demos? What value will AL add there compared to DemoZoo?

If we want to keep it, did you have specific ideas in mind about how it should look on the site?

Thanks!

**Comment by MugUK** [comment]
I reckon we just remove them as we can link to DemoZoo?

**Comment by stgraveyard** [comment]
I somewhat agree with MugUK. I am not the biggest fan of demozoo and how it looks. I think AL just looks way more 'fun'. But I dont know, to me it feels like reinventing the wheel. Maybe at one point, I don't know. Also demozoo's db is also open source, so we could even convert it into AL and build an automatic update or something :-)

**Comment by Brume-AL** [comment]
Today I would say the database is obsolete. We already have a lot to do with the games and menus db. We will never have time to take care of working on a demo database. On the other hand, as Maarten suggests, if there is a way to use DemoZoo database in some months/years (in the long run, not yet of course), that would be really great.

**Comment by nguillaumin** [comment]
Ok thanks for the feedback. So is there any objection in deleting the tables and data in the database and the screenshots? That would simplify the code a bit especially with crew editor as currently deleting a crew associated with demos is not possible, but it's also not possible to unlink the crew from the demo since there's no screen to do so...

**Comment by stgraveyard** [comment]
You know, deletion for me seems ok, but I just want to add one more thing...I'm currently thinking of starting a demoscene series on youtube. Still in thinking phase, but in that regard, maybe one day, like Bruno says, a demo section with a lot more fun compared to demozoo, could be cool. 
Nico, if you ever feel bored ... ;)
