### ISSUE TITLE
The Lemmings #40 - Can't copy CON.LNK from inside CONFLICT folder

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#145]
The Medway Boys version only works from floppy and I wanted a HD version so that I could update my Conflict Saved Game Editor.

So I found it on The Lemmings #40 but I get the read error below when copying it to my virtual HD under STEEM.

Can someone else check that it's not me going mad?

![2021-05-14](https://user-images.githubusercontent.com/17252699/118282321-13952d80-b4c6-11eb-8802-925a8bdc658b.png)

**Comment by nguillaumin** [comment]
It works for me under Hatari with EmuTOS.

**Comment by MugUK** [comment]
OK. I'll try with Hatari.

Cheers Nico

**Comment by MugUK** [comment]
The joys of a Windows-based emulator. CON is a port, like LPT1 etc. So Windows won't let you rename anything to CON, especially when LNK is also used to denote a shortcut link to elsewhere.

**Comment by nguillaumin** [comment]
Ahah, I see, nice :smile: I'm on Linux so I would not have seen this... Nice finding!
