### ISSUE TITLE
Music player for games

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#146]
Hi @stgraveyard @Brume-AL @MugUK ,

I have implemented a music player on the game page. It's deployed on DEV, you can now search for games that have music. I only added music to a few games for now, see: https://dev.atarilegend.com/games/566 for example.

The songs are coming from the SNDH archive. I have imported all songs and their metadata (title, composer, number of subtunes, ...) in the database and added screens in the new CPANEL to associate music to games:
- https://dev.atarilegend.com/admin/games/music : This one is a general screen that takes 50 random games and try to match music with them, with the option to review and associate in bulk
- I also added a basic way to edit the games and add music to them: https://dev.atarilegend.com/admin/games/games (In a way this is the beginning of re-implementing game editing in the new CPANEL).

The music themselves come from http://sndhrecord.atari.org/ . I asked the owner Adam if we could use it and he agreed, but he's waiting on his friend who is providing the hosting to confirm it's ok.

Please have a look and let me know what you think? I'll be travelling next week so I won't be able to make any fixes / changes until next week-end probably.

Note: The old CPANEL on DEV is broken currently because it's still using the old music tables. I have updated the code but the deployment is broken because the SSL certificate of a PHP tool we use has expired (https://pear.php.net/). I expect it will get fixed in the next few days.

**Comment by nguillaumin** [comment]
It did not work with Chrome because the songs were loaded over HTTP but AL is HTTPS and Chrome refused to load the music files. I implemented a workaround.

**Comment by nguillaumin** [comment]
Old CPANEL is also fixed on DEV now.

**Comment by stgraveyard** [comment]
> Hi @stgraveyard @Brume-AL @MugUK ,
> 
> I have implemented a music player on the game page. It's deployed on DEV, you can now search for games that have music. I > only added music to a few games for now, see: https://dev.atarilegend.com/games/566 for example.

Super clean and nice implementation Nico, in all resolutions. For me 100% what I like! Really really cool feature. 
2 little remarks : 

![image](https://user-images.githubusercontent.com/4339294/119357618-10f5bd80-bca8-11eb-97dc-4c349142a0ef.png)

1) Is it possible to change the aspect of the screenshot so it fits better? 
2) We should give credit where credits due, but not like this. The soundarchive text is too big and distracting. I will think about it, but maybe we can add the credits behind a hover icon or something, or just add the link in small font. 

> > The songs are coming from the SNDH archive. I have imported all songs and their metadata (title, composer, number of  subtunes, ...) in the database and added screens in the new CPANEL to associate music to games:

 So all songs are now in the DEV db, also the demo tunes and stuff we don't use? Which is no problem for me (maybe we use them in future), just wondering ...


> > * https://dev.atarilegend.com/admin/games/music : This one is a general screen that takes 50 random games and try to match music with them, with the option to review and associate in bulk

Very cool tool, but this is all just for testing I suppose? As we are on Dev server, right?

> > * I also added a basic way to edit the games and add music to them: https://dev.atarilegend.com/admin/games/games (In a way this is the beginning of re-implementing game editing in the new CPANEL).

I love the simplicity of the new cpanel, really nice.

Can't wait to have this in prod! 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks!

For the credit for me it's fine. It's not that big and you don't see it after a while. Plus without them there would be literally no music possible (assuming we don't want to use my dodgy YM player). I'd like to keep it somewhat visible. Compare with Lemon Amiga for example where they give credit to Exotica.

Yes all songs are in the DB. It's just a single table with 4,000 entries or so so not an issue. I have no way to distinguish game music from the rest unfortunately. For now it's only v4.5 on the SNDH archive as that's what Adam recorded, but they may record the latest (4.7) at some point. I hope it will also be an incentive for the SNDH guys to rip more songs.

For CPANEL, the random screen will stay, at least until we have assigned most musics to games. I thought it was a "fun" way to do it, it you have 5mn to spare you can just go to this page and assign a few musics... A bit like the "issues" page when you assign genres to games that miss one.

**Comment by stgraveyard** [comment]
I don't see any credit for exotica? https://www.lemonamiga.com/games/details.php?id=770#

Nico, the credit font is bigger than the actual music titles. Why not just add a nice small sndhrecord.atari.org at the very bottom of the box in a smaller font?

I really like the radom screenshot, was just wondering if it could be smaller as now (in my example) we have Remlins instead of Gremlins ...

**Comment by stgraveyard** [comment]
Nico, why not put this in prod already? So we can start linking music to the games? Like you say, we will do some if we have a moment free time...

**Comment by MugUK** [comment]
Nice feature. The only problem will be when a lot of PD games didn't have their own music - they just used Mad Max (or similar) tunes from other games/demos in their own games.

**Comment by nguillaumin** [comment]
This is an example on Lemon Amiga (I think the game you picked did not have music). Sorry I only have my phone with me:

![Screenshot_20210524-232534](https://user-images.githubusercontent.com/762512/119409320-6b623e80-bce7-11eb-92d5-d20a7a8c208b.png)

I would be ok to make the text a bit smaller, I'll try when I'm back.

Can't put it on prod yet, need to wait for Adam for final confirmation.

For the screenshot unfortunately it can only display square pictures. But I could resize it, although with some black borders on top and bottom?

For PDs it's fine, we can still associate the PD game with a music from Mad Max for example, that's the beauty of it 😊

**Comment by nguillaumin** [comment]
I have resized the cover screenshot to a square aspect ratio and reduce the size of the credit line.

**Comment by nguillaumin** [comment]
This is now deployed on prod.

**Comment by stgraveyard** [comment]
This is amazing Nico.

Some questions. Did you do any automatic linking? Or should the DB team now start adding music?

**Comment by nguillaumin** [comment]
No I did not do automatic linking, it's a bit difficult I think because we only have the name to base it on, and for example there are multiple games named "Tetris" that would be a match for a music of the same name... So I just did link a few for testing, but it has to be done manually.

**Comment by nguillaumin** [comment]
@stgraveyard I thought we could try to coordinate with the DB team to makes sure we are not duplicating the work. To that effect I made a spreadsheet that list all the folders of the SNDH archive: https://docs.google.com/spreadsheets/d/1KnDSuNGZxa6gmHyomdWrbg9r2J98-wK7NITbpAa0BNY/edit?usp=sharing

We can divide the work with people picking folders and going through to associate the music with games. I have written some instruction in the first sheet of the document.

Let me know what you think, and if you can share with the team if they're ok to use it?

**Comment by stgraveyard** [comment]
@nguillaumin I have sent the link to the team. Currently no time myself, working hard on new video. I did announce the update on Facebook and twitter today ;-)

**Comment by stgraveyard** [comment]
Nico, can you read these tweets from gunstick? 
https://twitter.com/GunstickULM/status/1399112000958050305

He wants to help with the music linking using scripting ...

**Comment by nguillaumin** [comment]
From what I understand it's not about the linking, he's proposing to re-record to MP3 all SNDH songs from the latest archive (v4.7) using an emulator (sc68). I thought of this as well initially but since Adam has recorded everything already it's not necessary. The only benefit would be to use the latest version of the SNDH archive (Adam has recorded v4.5) but we would lose all the digi tunes as sc68 does not support them well. Plus Adam recorded the real hardware which is nice 🙂 I hope he will record v4.7 of the archive at some point...

**Comment by Gunstick** [comment]
My idea was to base on the game name, and retrieve matching suggestions from the sndh table. So to associate you don't need to go through 4000 songs. 
No luck with PD games though. And that's where this will be the most useful feature when people ask themselves what music is in that game.
As it is possible to have the same music in multiple games, the reverse info would be useful too: "music also used in these games: ..." and if you like, also do a "music used in demos here <link to demozoo>"
And demozoo could link back to AL (if they like...)

**Comment by nguillaumin** [comment]
I believe that's more or less what I implemented. There's a page in the admin where you get a list of games and candidate songs, that you can associate. Same when editing a single game.

![1](https://user-images.githubusercontent.com/762512/120220089-829bb180-c23c-11eb-9b3e-cc978676d185.png)

![2](https://user-images.githubusercontent.com/762512/120220091-83344800-c23c-11eb-8bb5-31736f720559.png)

Unfortunately I don't think it can be automated much more than that because there are too many false positives. For example:
- Multiple games named "Tetris" that would match the song named "Tetris" from David Whittaker
- Songs that have the same name of a game by chance, but are unrelated to the game. Typically if a game has a generic name like "Switch" or "Myth", there will be tunes with the same names but that are unrelated to the game
- Mismatch between UK/US names (e.g. Skateball vs Skate Wars)
- Mismatch in wording or spacing (e.g. Star Wars vs Starwars, not a good example but just to give you the idea)

So it has to be manually reviewed to ensure good quality I think :worried: 

Let me know if that's what you had in mind, or something else?

> the reverse info would be useful too

Yes, something to consider once we have a bit more music associated to games in the database.

**Comment by nguillaumin** [comment]
The other thing to consider is that we have to check that the games have the proper credits for the music, so we need to go through them one by one anyway...

**Comment by stgraveyard** [comment]
Hi Nico, 

Got a new pm on Twitter from Gunstick : 

_Hi, I wrote a message that someone is recording digimusic from games. Did not get an answer. So I asked him if he could do some mp3. I got them from him. Grab the stuff here._

And here is the file : https://www.filemail.com/t/aSmgeRnz

Can we also implement MP3 in the current player? Is this of any interest? This should be for digi tracks I think. 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
We can use MP3, that's what's the actual player is using, MP3 sourced from sndhrecord.atari.org. However I would have to import them in a completely separate table and put the files in AL. I'm not sure it's worth the effort just for a handful of tracks, and some of these tracks are already in the SNDH archive anyway in digi form (See Xenon 2 or Great Giana Sisters for example).

So for now I would say no, unless they can share a larger collection of tracks that are not in the SNDH archive.

**Comment by Gunstick** [comment]
I got the idea because the player is just using mp3, so any sound will work. The youtuber said he would create about 10 more videos, and also do the mp3s. In any case, having the digi track of those games will make some people happy.
