### ISSUE TITLE
CPANEL - MUSIC - Activity / Recent changes

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#147]
Hi Nico, 

I have linked some music to certain games, but my changes are not registered in the DB changes table. 
I think this is something that has slipped under the radar?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks, well spotted. I did populate the changelog when editing an individual game, but not in the "bulk assign" screen. It's fixed now.
