### ISSUE TITLE
Credits in the interview section - bug?

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#149]
Hi Nico,

You have any idea why droid se is not shown in the credits section of this interview : https://www.atarilegend.com/interviews/51

![image](https://user-images.githubusercontent.com/4339294/120828202-88570700-c55c-11eb-8c36-56f7ae550068.png)

I think we have a new bug? 

![image](https://user-images.githubusercontent.com/4339294/120828285-a4f33f00-c55c-11eb-8757-3423445441fb.png)

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Ah yes, I made some changes in the code connecting Games with Individuals and I introduced this bug. Should be fixed now.

**Comment by stgraveyard** [comment]
Perfect, thanks a lot!
