### ISSUE TITLE
Can't add/edit a game to the database 

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#150]
I tried to add a game to the database but i got this message:

![atarilegend](https://user-images.githubusercontent.com/12120244/121804030-94ba1e80-cc44-11eb-85d4-d5c15ab517d9.png)

Despite of the bug, the game has been added, but I can't edit it with the legacy nor the new control panel.

Thanks in advance for your help Nico 👍😉

**Comment by nguillaumin** [comment]
Yes, I came across the same issue, it's related to the new feature to add video to games. The changelog system in the old CPANEL did not recognize the new changelog entries. It's fixed now, sorry about this.

**Comment by Brume-AL** [comment]
Thanks Nico, it works perfectly now 🙂

**Comment by stgraveyard** [comment]
Awesome we have such a developer on board! Hurray for Nico!

**Comment by nguillaumin** [comment]
Well I don't know 🤔, I caused the bug in the first place! 😂
