### ISSUE TITLE
Main SITE - Front page - old AL tile is back

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#151]
Hi Nico,

For some reason, the old AL tile is back on the front page : 

![image](https://user-images.githubusercontent.com/4339294/123214499-98149c00-d4c7-11eb-8f67-0f2af7054800.png)

Can you check what is going on?

Thanks,
Maarten

**Comment by nguillaumin** [comment]
The old AL tile is shown if there's a problem retrieving the last 3 videos from YouTube. It looked like the URL I used for that (https://www.youtube.com/feeds/videos.xml?channel_id=UCN7ePamELHkBVAHwXa4cubg) did not work anymore. But now it works again! And the videos are back on AL.

So some kind of transient YouTube problem it looks like.
