### ISSUE TITLE
MAIN SITE - Create account - Issue with Captcha? 

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#153]
Hi Nico,

I just got following message on facebook : 

_Hello, I would like to register on this site (www.atarilegend.com), but not possible, The h-captcha-response field is required. But impossible to see the h-captcha. How to do ? do you have visitor access, thank you and have a nice day. i have used multiple browsers and update, but still the same. Cordially_

![image](https://user-images.githubusercontent.com/4339294/127311419-55d8acb5-9bed-469c-8419-d4ccce054052.png)

When I check this myself in Chrome, I also have the issue : 

![image](https://user-images.githubusercontent.com/4339294/127311502-b096ea63-adfc-4cad-94b2-b0403de87e3e.png)

Do you have any idea?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I think I know what the problem is. I'll try to have a look in the next few days.

**Comment by nguillaumin** [comment]
Should be fixed now. I introduced the bug by mistake when I added videos on game pages I think...

**Comment by stgraveyard** [comment]
Thanks a lot
