### ISSUE TITLE
MAIN SITE - UPDATE about page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#155]
Hi Nico,

This is nothing urgent, but I was wondering, if I sent you the text (and maybe a screenshot), would you do an update of the about page HTML? I think it is a neat page and we should update it every few years. These are the section I would add, but if you or anyone else thinks more highlights are needed, let me know. 

- November 2017  (people logo) : A new developer, Lynxx, joins the AL team. With his professional webdevelopment skills, the future of the project is looking bright! 

- January 2018 (Wrench logo) :  The first part of the Atari Legend project has gone open source. From now on, any developer who is interested can download the full database (except the sensitive user related data) and all the screenshots, boxscans and other graphics used for their own project.

- May 2019 (Screen logo) : AL starts a Youtube channel

- August 2020 (Wrench Logo) : The code for the AtariLegend website is now open-source! We wanted to open the code as well for a long time, but it took some time to reach that point. We now have our own GitHub.

- December 2020 (Wrench logo) : AL gets a complete redesign and code overhaul, based on Bootstrap, making everything more accessible for possible future developers. 

- April 2020 (Wrenchi logo) : Stonish.net, the website by fellow member Brume featuring the biggest collection of Atari menudisks, is merged with Atari Legend.

What do you think?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
This is done on dev, please have a look: https://dev.atarilegend.com/about

**Comment by stgraveyard** [comment]
Very cool. One more suggestion for the top tile : 

![image](https://user-images.githubusercontent.com/4339294/128204551-185585d5-ccd7-4332-9c20-ec74445e08d2.png)

I think that would be better?

**Comment by nguillaumin** [comment]
Done, and being deployed on prod now.
