### ISSUE TITLE
MAIN SITE - Updates box

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#156]
Hi Nico,

In the main games section we have this box : 

![image](https://user-images.githubusercontent.com/4339294/127993728-0318b818-9290-47bc-95e7-2b28c87d3030.png)

I think we need to decide what to do with it, because I think it is not up to date anymore. 

1) remove it 
2) check the code and update (add music updates for example as well). Also the link to changelog does not work anymore.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
It was a bug, it was only counting the data of each month up to the day of the current month (so today being August 3rd, it would count July 1st - 3rd, then June 1st - 3rd, etc.). It should look better now, and I also removed the link to the changelog.

Available on dev, will be deployed on prod with the other change on the About page.

**Comment by nguillaumin** [comment]
Being deployed on prod now.
