### ISSUE TITLE
MAIN SITE - Log on issues

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#157]
Hello Nico, 

We are currently facing a problem with the account verification and log on process. I don't know where this is coming from. 
When you already have an account and are logged in, the AL site looks like this : 

![image](https://user-images.githubusercontent.com/4339294/132386150-4355208e-436a-491b-81af-743bdfeeba6c.png)

When you try to log in, the credentials are never accepted : 

![image](https://user-images.githubusercontent.com/4339294/132386253-d9a05823-d1db-4e14-b140-d0776b9013ea.png)

Can you please have a look when you are back from holiday? 

Thanks,
Maarten

**Comment by nguillaumin** [comment]
I had the same issue when you reported it initially, but now it seems to work, but I did not change anything, so  that's odd... Could you re-test? Does it work for you now?

**Comment by stgraveyard** [comment]
Also got a message from the person who mentioned this bug. He confirms everything is solved.

**Comment by nguillaumin** [comment]
Ok good, although it's not ideal to not know the cause. Possibly some database issue, but I would have expected a hard error instead of something like this...

**Comment by stgraveyard** [comment]
You think a DB issue? What kind? data corrupt?

**Comment by nguillaumin** [comment]
Not sure, I don't think so because it resolved itself. Maybe a connection or query issue, perhaps the hosting provider had issues at that time or something, that caused queries to return bad results.
