### ISSUE TITLE
MAIN SITE- Game detail pages - No link to review (when not logged in)

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#158]
I have a feeling, when we are not logged in, the review of a game is not linked to the actual game. Take Zool for example. This game has a review, but still, when nog logged in, I only see this : 

![image](https://user-images.githubusercontent.com/4339294/132395609-d2035223-36bc-4dcc-9322-6b1d59010322.png)

This is not OK and wasn't like this in the past.

**Comment by nguillaumin** [comment]
It works for me, the reviews are displayed event if you're not logged in:

![image](https://user-images.githubusercontent.com/762512/132942225-133fc0d9-fa53-469e-9cfd-5b91538036a2.png)

I didn't change anything though, so that's odd. Could you re-check?

**Comment by stgraveyard** [comment]
Indeed, now they are :-o

![image](https://user-images.githubusercontent.com/4339294/132944123-e2601901-92b4-4f99-9733-a6d8ba61b87d.png)

Weird, really weird...
