### ISSUE TITLE
Game detail page - No boxscan when image uploaded? 

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#162]
Hi Nico,

When we have a disk image loaded I seel this : 

![image](https://user-images.githubusercontent.com/4339294/133669898-6a7b0768-1ea8-4ef7-9e2d-f96d4db8a112.png)

Empty right side.

When no disk image uploaded I see this : 

![image](https://user-images.githubusercontent.com/4339294/133669970-1faccc32-136f-4b6e-86c8-fc78bc631c7e.png)

I think we always need a boxscan or something on the right side.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
It's unrelated to the presence of a disk or not. It's that this specific release has no boxscan (remember that we changed the boxscans association to be with release and not games, since each release can have a different box).

I have moved the "Submit info" tile on the right to fill the spot.
