### ISSUE TITLE
Change  STAC (The ST Adventure Creator) to STAC - The ST Adventure Creator on Dodgysoft 121 disk

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#168]
How do I rename a title that's on a compilation disk?

The Dodgysoft disk 121 in question doesn't link to the game page for "STAC - The ST Adventure Creator" because it's been labelled as "STAC (The ST Adventure Creator)" instead.

I tried downgrading item 1 to item 4 and then creating a new item 1, but it told me there was an error in the Game field? So I changed item 4 back to item 1 and posted in here instead before I make any more errors :)

**Comment by MugUK** [comment]
Sorry, but I can't get this to work. I enter the correct name and a number 1 for the entry on Disk A, and it hits me back with an error message.

"The game field is required."
![ErrorFixingStacEntry](https://user-images.githubusercontent.com/17252699/137109216-65c7e4c1-7b34-4d5e-94c1-3588a39adc6f.png)

**Comment by nguillaumin** [comment]
Closing this as it seems it was solved.
