### ISSUE TITLE
BBCode emojis are not processed

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#170]
I saw on some older comments that BBCode supported emojis like `:lol:`  or `:cry:` . Currently they're not processed so they don't show up in the comments.

We should fix this. The list of supported emojis can be found in the legacy source code: https://github.com/atari-legend/legacy/blob/master/public/php/lib/functions.php#L247

**Comment by stgraveyard** [comment]
I did this on purpose Nico. I think they really f*ck up the design and people leaving comments tent to overuse them, which was an eye sore for me, I don't want them, so I removed the support. But feel free...I rather like ascii emoji's like ';-)' or ':-D'  ...

**Comment by nguillaumin** [comment]
OK, I thought it was something I overlooked when I rebuilt the site, I did not realize they were already disabled. I'm also fine with the ASCII ones, but the problems are the ones like `:lol:`
I'll have a look if I can find a set of emojis that would work with the design, otherwise I'll leave it as is.

**Comment by nguillaumin** [comment]
I have implemented it on dev if you want to have a look. I think it gives a bit of life to the site so I like it :wink: Check out the comments on Barbarian for example: https://dev.atarilegend.com/games/186

I also realized that people can just use regular emojis anyway (in fact it didn't work but I fixed it) so maybe it doesn't matter as we can't prevent people from entering random emojis!

**Comment by stgraveyard** [comment]
It is ok for me Nico. It even doesn't really bother me anymore. I don't know :-) I remember I was even experimenting with 'blue'-ish emoticons, just so they could fit better in the design :-) But it is ok. 

Thank you.

**Comment by nguillaumin** [comment]
Ok cool. I tried to find a blue-ish set but I did not find anything that looked nice.
