### ISSUE TITLE
Banner Animations

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#171]
Hi Nico,

These are incredible, super fun to watch. There is one animation that should be removed : 

![image](https://user-images.githubusercontent.com/4339294/147126735-2f93164b-4628-4d51-b159-15f0c412c6dc.png)

As you can see, it is not transparent. Please just remove it. too bad, it is one of my favorite games ;-)

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Interesting, I did not see it, neither on my phone when I read the GitHub issue. I think because of the night light on my computer + phone the 2 blacks are hard to distinguish... Anyway I was able to fix the GIF so it's transparent now.
