### ISSUE TITLE
Sort by Dev Tool? (I honestly thought we had this option)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#177]
As per the post on AF (https://www.atari-forum.com/viewtopic.php?t=16042) where both Atarimania and AtariUpToDate websites can filter on only SEUCK games, I went to try it on AL and found we can't do this.

I thought this was an option that we could do?

Could we add this filter option for titles written using 3rd party tools, such as: STAC, SEUCK, 3D Construction Kit etc.

**Comment by nguillaumin** [comment]
I added a new filter in the search page.

On the long run I'd like to rework the advanced search because there are a lot of options that are missing. I'd like to get to something similar to the Lemon Amiga one perhaps... https://www.lemonamiga.com/games/advanced_search.php
