### ISSUE TITLE
Freescape (Commercial) and 3DCK (Shareware)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#178]
A quick heads up that I'll take a look at both of these engines as Freescape was the engine that Incentive used for all of their commercial releases, e.g. Castle Master.

Whereas 3D Construction Kit is the tool they sold which people then used to make their own shareware/public domain 3D games. We've got some listed incorrectly, so I will tweak the entries.

(Thanks for the new Engine search option Niko!)

**Comment by MugUK** [comment]
All done. We have more entries that Atarimania and the one title that they had, that we didn't (Evil Dead Cabin) is now in our DB too.

**Comment by nguillaumin** [comment]
Great!
