### ISSUE TITLE
How do I group titles in a Set?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#179]
Along with the CASA updates, I've been getting help from Dean (now Deano) Sharples with regard to all of his STOS games and games written using his STOS Adventure Creator.

I found a Granny's Garden (along with Grannies Garden) and this was an incorrect name for a set of three games released as the "Silly Software Collection". I've renamed "Granny's Garden" but I've never done a set before.

How do I add the three titles Deano has told me were in this collection into a Set?

**Comment by nguillaumin** [comment]
The only concept we have for this is "Series" I think. It's still in the legacy CPANEL:

![series1](https://user-images.githubusercontent.com/762512/163016562-ad10cfea-bc61-4c5f-a072-5f1c577116f6.png)

Here you can create a new series, and then edit it to add the games that are part of the series:

![series2](https://user-images.githubusercontent.com/762512/163016706-28b20221-0b80-4b33-b9c8-d8d0bad5cf25.png)

Then it's displayed like that on the site:

![series3](https://user-images.githubusercontent.com/762512/163016838-b202de35-c6b7-4d0a-acee-e7e827dffbfc.png)

Hope this helps?

**Comment by MugUK** [comment]
I'll give it a go later on today.

**Comment by MugUK** [comment]
Done. I'll close off this log now.
