### ISSUE TITLE
Adding missing adventures

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#181]
With the work I'm doing liaising CASA solutions with AL, I've noticed we're missing quite a few adventure games. Most of these, by Zenobi Software, are recent-ish ports from ZX Spectrum originals. 

Am I allowed to upload these to the database to make them available yet or are we still hanging back for now as we're just on the menus for now?

**Comment by nguillaumin** [comment]
I would say go ahead, no reason to hold off in my view. I have been uploading the recent dumps by Cb...

**Comment by MugUK** [comment]
OK will start doing that. A lot are ports of old ZX Spectrum adventures that have been converted using modern tools like DAAD and a clone of Inform (PunyInform). Slowly adding these engines to the database too.
