### ISSUE TITLE
Releasing saved game editors for Atari Legend (FGC) releases?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#182]
I've rewritten/upgraded an old cheat (for Battletech) but now it's using proper .RSC files and looks "pretty" :)  I've tested it against cb's version, which is working 100% from HD, unlike PPera's version :)

I'm going to release it at Silly Convention in Gdansk (Poland) in August, along with a few others that are being upgraded.

However, as my .TXT file mentions that cb's version is the only 100% working one, people are going to want to download it. Can we aim to get all of cb's releases ready for August and say it's our "gift" to Silly Convention? Especially as it's a 50th year of Atari celebration?

**Comment by nguillaumin** [comment]
Would be fine for me, in fact I already uploaded the latest dumps of cb, for example: https://www.atarilegend.com/games/release/20381

Happy to help, but I would need a list of the dumps to upload and where to get them from.

**Comment by nguillaumin** [comment]
Would be fine although the direct link might change because it contains the ID of the dump. So I would recommend giving the link to the specific release (Like I did in my example for Champion of the Raj above).

Closing this, assuming there's nothing else to do on the site.
