### ISSUE TITLE
Suggestion/Question : Max width of website

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#184]
Hi Nico,

This week I have bought myself a nice 32 inch widescreen productivity monitor, most for work, so I can work with SAP and Excel and WORD on 1 screen. You know how it goes ... 
Anyway, it is fantastic and I'm now working in 4k (3840 * 2160). But when I look at the website now I see this: 

![image](https://user-images.githubusercontent.com/4339294/182470859-a27a64fd-1237-4517-8063-4fb330b14b3c.png)

![image](https://user-images.githubusercontent.com/4339294/182470890-c38b0a96-c490-4351-a594-d5b2ecd801b0.png)

It is not bad, but just lots of space now. But it is not bad, I mean, I have seen much worse.

However, when I look at LemonAmiga I see this : 

![image](https://user-images.githubusercontent.com/4339294/182471056-feb4ee3d-c299-426b-84f2-dc7cf9f6bd60.png)

This got me thinking. Wouldn't it look better if we add a max width of 1920 or something? 

(Have I asked this before?) 

Opinions needed.

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Hi, I have added a max-width on the dev site if you want to try it?

**Comment by stgraveyard** [comment]
Nico, I am on holiday in France, will check next week. Thanks a lot.

**Comment by stgraveyard** [comment]
Hi Nico, 

What is the max width installed now? I remember I had this also build in in the original skin, and in the side I had a Atari Bomb as a watermark to fill up the black space. 

Maarten

**Comment by nguillaumin** [comment]
It's 1920px on the dev site: https://github.com/atari-legend/atari-legend/blob/development/resources/sass/_common.scss#L72

**Comment by stgraveyard** [comment]
This is legacy cpanel :  

![image](https://user-images.githubusercontent.com/4339294/183486470-29dad73a-d885-4573-8118-bee99a8e1133.png)

You see the bombs. I think that looks good, but it is not ok when scrolling down. Also this : 

![image](https://user-images.githubusercontent.com/4339294/183486616-65d6f7bc-7198-4d6e-aee7-fd1571a50522.png)

So yeah Nico, I don't know right now. I think a max width looks good, but the widgets don't align? 

Maarten

**Comment by nguillaumin** [comment]
I'm not sure what you mean with the "bombs"? Can you highlight on the screenshot maybe? Also don't see what is wrong when scrolling down?

To clarify I did not change anything on the legacy CPANEL, only on the main site.

**Comment by stgraveyard** [comment]
Sorry Nico, I mean the bees. In thr screenshots above you vaguely see them in the black parts of the side...

**Comment by nguillaumin** [comment]
Ah, yeah it's again a case of my screen contrast, I see only black...

I have added the bees. I have put them to repeat across the whole background, which is different from CPANEL where they are only on the top-left and bottom-right. Let me know what you think?

**Comment by stgraveyard** [comment]
Hi Nico,

Thanks a lot. For me it is a go. I have been working on my new big screen monitor now and I can not get used to the super wide view. For me the design is not made for that. I would really like the restriction personally, like on dev. Love what you did with the bees! 

If nobody else complains, and if you also prefer the 1920px, please put in prod.

Thanks,
Maarten

**Comment by nguillaumin** [comment]
I agree I think it looks good. I have triggered the deployment to prod.

**Comment by stgraveyard** [comment]
Thanks a lot, this is so much better now.
