### ISSUE TITLE
"couldn't get number of mag reviews" error when trying to edit a program's info

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#190]
I was watching a stream from the CRX and in it Kenneth Hurley was being interviewed and a tidbit was that after he'd ported Sword of Kadash to the ST, he wrote Copy-II-ST - an early ST software deprotection tool. 

I clicked on the pen icon next to the title of the game, so I could add this info and the above is the error message that I got.

I'm guessing that this is linked to magazines addition being coded? I've tried a few other random games and the same error occurs.

**Comment by nguillaumin** [comment]
I see, it's on the legacy cpanel, I modified the existing magazine tables but did not update the code there. I'll try to have a look this week.

**Comment by MugUK** [comment]
No worries Nico.  I can add the extra info about Ken when it's fixed.

**Comment by nguillaumin** [comment]
Should be fixed now.

**Comment by stgraveyard** [comment]
great news, this was an annoying bug. Glad it is solved. Thanks a lot.
