### ISSUE TITLE
Issues when entering Hints/Tips

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#194]
I thought I'd skive off work for 20 minutes and finish off the first Atari ST Review. A few things I've noticed:

a) I can't enter Dungeon Master as there are too many add-ons that appear first in the matched titles list that appears.

b) The auto-sort doesn't work with titles on the same page. So now I've got Cadaver appearing in the list before Another World. Have I got to delete all the entries and start over again to fix this?

**Comment by nguillaumin** [comment]
Hi,

> a) I can't enter Dungeon Master as there are too many add-ons that appear first in the matched titles list that appears.

Yeah it's a similar issue when there are duplicates in the list and how to distinguish them. I will work on this, although not sure of the solution here. Maybe just make a bigger list :wink: 

> b) The auto-sort doesn't work with titles on the same page. So now I've got Cadaver appearing in the list before Another World. Have I got to delete all the entries and start over again to fix this?

The auto-sort only considers the page number. If 2 rows are on the same page they are sorted arbitrarily. I think the same on the main site. I could add an extra sort by game name I guess...

**Comment by MugUK** [comment]
> Yeah it's a similar issue when there are duplicates in the list and how to distinguish them. I will work on this, although not sure of the solution here. Maybe just make a bigger list 😉

Is it possible to sort by length of the game title. That way, in theory, Dungeon Master would appear first, then Dungeon Master 2: Chaos Strikes Back, then the remaining titles?

> The auto-sort only considers the page number. If 2 rows are on the same page they are sorted arbitrarily. I think the same on the main site. I could add an extra sort by game name I guess...

Yes please.

**Comment by MugUK** [comment]
Can I add Lotus Turbo Challenge to the list of issues - I can only see #2 & #3 but not the original title as it can't fit on the screen.

**Comment by MugUK** [comment]
> Can I add Lotus Turbo Challenge to the list of issues - I can only see #2 & #3 but not the original title as it can't fit on the screen.

I found a way around it for now. Make sure Auto-sort is selected and add a new row. It will go to the top of the list. Enter the game name first, then the type, then the page number. As soon as you enter the page number it will move to where it's supposed to be.

**Comment by nguillaumin** [comment]
I have added a secondary sort by game name.

> Is it possible to sort by length of the game title.

It's not that simple I think, unfortunately. What we need is really a sort by "best match" but MySQL does not offer that. If we do by length it will work for these special cases like Dungeon Master, but will have side effects. For example below: 

![3](https://user-images.githubusercontent.com/762512/194612896-c224b30e-2f12-498b-9774-0378399f3ee7.png)

Zork III appears in the middle because it's shorter than the following "Dungeon Master" titles...

> I can only see https://github.com/atari-legend/atari-legend/pull/2 & https://github.com/atari-legend/atari-legend/pull/3 but not the original title as it can't fit on the screen.

You should be able to scroll down once the suggestions are displayed, for me it works.

**Comment by nguillaumin** [comment]
I made tweaks to the auto-suggest which I think make it more useful now, incorporating the game name length in the approach.

**Comment by MugUK** [comment]
Many thanks for these tweaks.
