### ISSUE TITLE
First pass of Atari ST Review (issues 1-10) - are we going to review other submitter's work?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#195]
Not a problem as such, but there could be some improvements made to the links once all the extra features are added (separate icons, compilation boxes of games etc), but for now, there are now 10 issues of Atari ST Review indexed. 

Quite glad they were a late edition to the scene and didn't do mostly game reviews as it made this first attempt a lot easier :)

**Comment by nguillaumin** [comment]
Very nice, well done!

Personally I won't have time to review other submitter work :wink: But I'm open to feedback on my work of course.

**Comment by nguillaumin** [comment]
Also feel free to use the "Discussion" section in GitHub for things that are not directly a bug / issue: https://github.com/atari-legend/atari-legend/discussions

**Comment by MugUK** [comment]
Ah right, didn't know about the discussion area.
