### ISSUE TITLE
Interview (and review) section on a widescreen

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#201]
Hi Nico, 

Ever since I started working on my very wide screen, I have now noticed some minor layout 'issues'. And I was just wondering if there is an easy quick fix for it. 

As an example, a lot of my interviews don't look as nice anymore. Take Francois Wunshel : 

![image](https://user-images.githubusercontent.com/4339294/197193434-0fdeff5c-d3d1-458b-8356-96ede6339ac4.png)

This is the bottom of the interview. Because the resolution changed there is now a lot of space at the bottom. And I was wondering ,since I noticed you did another change to the interview and review section a while back, when it is the opposite, you have done this : 

![image](https://user-images.githubusercontent.com/4339294/197193681-78d68d90-f646-44c8-92aa-c3f019b72b8e.png)

This is really nice. So this got me wondering, is it also possible the other way around? That the pics go to the left when there is no more text?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Unfortunately I don't think so. There must be at least one "column" defined for the rest of the content to float around it. I don't think having "double floating" column is feasible...
