### ISSUE TITLE
New bot accounts at AL

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#204]
Hi Nico,

I think we have some kind of new bot accounts being made regularly. Look : 

![image](https://user-images.githubusercontent.com/4339294/202304071-9af38821-3d10-4110-b3ab-58d1736786d0.png)

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Indeed :disappointed: Not too sure what to do about it. The captcha we have in place should stop these... I guess I could add a validation rule for the email to prevent addresses with too many dots + GMail, although that might catch some real users maybe.

**Comment by stgraveyard** [comment]
Nico,

What about an auto delete of accounts that are not verified (inactive - no click on link in email which is sent) within 12 hours?

Cheers, Maarten

**Comment by nguillaumin** [comment]
Good point. I assumed these bots also verified emails, but if that's not the case it helps. I added a scheduled task to do exactly that (with a delay of 24h, I thought 12h might be too short).

**Comment by stgraveyard** [comment]
Nico, another smal request. Is it possible NOT to add unverified users in the 'who is online' at the bottom of each page?

**Comment by nguillaumin** [comment]
Absolutely it makes sense. I have made the change.
