### ISSUE TITLE
Bottom of the page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#205]
Hi Nico, 

Sorry to act so autistic about this, but the bottom of the page, was this always like this? with the bottom green line and the BG line above it. all of a sudden this looks so weird to me.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/4339294/204393729-832de0ce-4402-4940-8c69-4c31886f4ebe.png">

Maarten

**Comment by nguillaumin** [comment]
I think it's the same as before? I tried to get it as close as possible. You can compare with the legacy cpanel. At a glance the margin between the list of users and the bottom bar is a bit bigger, but I'm on mobile and not desktop.

**Comment by stgraveyard** [comment]
You are correct, sorry for wasting your time Nico.
