### ISSUE TITLE
Typo on the main game page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#208]
Hi Nico,

Facebook user Pavel sent me following screenshot with a little typo on the main game screen : 

![321413394_941997866785126_3592296771628530637_n](https://user-images.githubusercontent.com/4339294/210381496-96f410e9-2097-4677-a634-4d33b3181b6b.png)

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Thanks, I fixed it.
