### ISSUE TITLE
Lemon64 website update and new file for linking with AL

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#209]
Hi Nico, 

I got the following message from Kim Lemon : 

--------------------------
Hello Maarten!

I have attached a CSV with all current Lemon64 => Atari Legend links.
[lemon64-atari-legend.csv](https://github.com/atari-legend/atari-legend/files/10500336/lemon64-atari-legend.csv)

It would be great if you could import this data and update your links to Lemon64. Also, please let me know if I miss any Atari ST links in my database.

Lemon64 now uses slugs instead of ID in URLs, for example: https://www.lemon64.com/game/bomb-jack

While the old URLs 301 redirects to the new format, I would really appreciate if you link to Lemon64 in this new format, including https instead of http.

/Kim
-------------------------------------

I don't know if this is doable? 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
URL slugs, nice! I want to do the same for us for a long time :wink: 

Yes it's possible, but it's a bit of work as we can only store an ID for the Lemon64 link, so we need to change the DB structure. I will have a look but not sure when I'll have time.

I did not find a way to edit the Lemon64 or LemonAmiga link in the legacy CPANEL, is that right?

**Comment by nguillaumin** [comment]
Well that was a bit easier than I thought. I was able to make the change.

However it revealed a flaw in the DB structure for this. For example https://www.atarilegend.com/games/15 , the C64 link is duplicated. The DB structure for this is a bit wrong. Also we don't have any way to edit this in CPANEL so I will need to build the screens in the new CPANEL. But no big deal in any case, I'm adding that to my list :smile:

**Comment by stgraveyard** [comment]
Thank you so much Nico! I'm so happy you are doing all this.

Cheers.
