### ISSUE TITLE
New issue in the change log page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#210]
Hi Nico,

I see you have been doing updates to php 8.2, so I think the following new 'bug' is related to that? 

![image](https://user-images.githubusercontent.com/4339294/215296699-b28ec11a-2a24-43e6-8b42-66936a000c38.png)

This is in the changelog page of the old cpanel. everything seems to be working fine, just this warning.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks. Not sure what happened as I didn't touch the legacy CPANEL in practice. Weirdly it was set to use PHP 8.1 in the hosting control panel which I don't remember setting. Maybe Brume did it? In any case I think I was able to fix all issues.

**Comment by stgraveyard** [comment]
Hi Nico, 

I'm getting this one on the interview main page of legacy control : 

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/4339294/215607111-d3b8f654-5824-4ab0-a826-068cc022e468.png">

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks, I fixed it. Also went through the other page and fixed other warnings.

**Comment by stgraveyard** [comment]
Nico,

We now have another issue?

<img width="992" alt="image" src="https://user-images.githubusercontent.com/4339294/215975264-7d3a1c21-72e9-4939-bf09-4f8121d70de7.png">

**Comment by nguillaumin** [comment]
Ah, I only deployed to dev by mistake. Now pushed to prod, the build is running...
