### ISSUE TITLE
Bugs when a new game is added to the database

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#213]
Hi all,
I added an educational game to the database this morning:
https://legacy.atarilegend.com/admin/games/games_detail.php?game_id=7695#gd_developers
I got some errors when I added the screenshots, but managed to save all data.
But now something is broken. I can't display this game on the front site. And we try to make a search in the engine, I get this error message:
![image](https://user-images.githubusercontent.com/12120244/220869693-19c14a9a-eb20-4657-9fdd-932a86aaafa0.png)
Try this search, for instance.
https://www.atarilegend.com/games/search?title=english

Looks like I break something when I added this stuff to the database...

Thanks in advance for your help.

Brume

**Comment by nguillaumin** [comment]
This is due to the new URL slug feature. The legacy CPANEL does not put a slug in the database, which causes the issue. Then editing it in the new CPANEL was also not possible as it's also using the slug in the CPANEL URL.

I was able to fix it directly in the database. However to prevent this I need to:
- Disable game creation in legacy CPANEL (only in the new one)
- Change the new CPANEL so that game URLs still use the ID, just in case there's another issue with slugs later

**Comment by nguillaumin** [comment]
Now applied the 2 fixes from above.

**Comment by Brume-AL** [comment]
Thanks for the fix, it works like a charm now.
Also may I quit the legacy CPANEL and use the new one, now?

I found a small bug: the game added is displayed correctly here:
https://www.atarilegend.com/games/learning-english-green-line-4

But it doesn't work when I use the search engine from the top bar.
![image](https://user-images.githubusercontent.com/12120244/221051449-06ffcfae-0f9e-432a-9687-c3ac0d9b4148.png)

When I click on "Learning English Green Lite 4", it goes to this page:
https://www.atarilegend.com/games

**Comment by nguillaumin** [comment]
I can't reproduce this, I am sent to the right page when I click on it. Is it still happening for you? Which browser are you using?

**Comment by nguillaumin** [comment]
> Also may I quit the legacy CPANEL and use the new one, now?

Yes, but I did not re-implement 100% of the screens yet. At the game level I think game facts are missing, and the release screens are not there yet. So it's an uncomfortable "split" for now until I can complete the implementation.

**Comment by Brume-AL** [comment]
> I can't reproduce this, I am sent to the right page when I click on it. Is it still happening for you? Which browser are you using?

You're right, there was an issue with the cache of my browser. I tried in private mode, and the search engine leads to the correct page. After deleting the cache of Edge, it works fine. Problem solved, thank you.
