### ISSUE TITLE
2 x Games not linking properly from Serenade 59

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#216]
Neither 'Gone To The Dogs' nor 'Twinz' link properly. 

Gone to the Dogs is the title in the New CPanel but the menu list refers to 'Gone To The Dogs' - is this just a capitalisation issue in the title?

Twinz - I can't see what's different between the listing on Serenade 59 and the New CPanel entry.  But if you click on the link, it just returns to Serenade 59.

I've seen this happen in other Serenade menus too, but wasn't quite sure if it was me clicking something incorrectly, or the database entries.

**Comment by nguillaumin** [comment]
Well spotted! The issue is that these games are both in the games table, and in the "software" table used for the menus. That's also why they show up twice in the auto-complete:

![twinz](https://user-images.githubusercontent.com/762512/232230424-98dc8093-43a3-4b7a-b12c-aad0f6e5b507.png)

The first one will display the [game page](https://www.atarilegend.com/games/twinz), and the second one the ["software" page](https://www.atarilegend.com/menusets/software/1464) which lists all menu that contain that software (compare for example with [FastCopy Pro](https://www.atarilegend.com/menusets/software/4)).

I think it dates from the import of the Stonish data. In most cases the games on the menu were linked to AL game IDs so I could make the link, but there are some entries that did not have an ID, so I had to keep them as "software" without being able to link them.

I'll think of what we can do. At least extract a list of all "software" of type "game" (they are tagged as such) and see how to re-link them, manually in the worst case.

![software](https://user-images.githubusercontent.com/762512/232230613-e0fa3f0e-1cc1-4a12-bf04-c20cf62afaf8.png)

**Comment by nguillaumin** [comment]
There seem to be 140 occurrences of this:

```
3-D Tic Tac Toe
3D-Calc
Agony
All Blocked Up
Alphabet Mix
Atom Smasher
Blackjack And Solitaire
Boogey Man
Borodino
Boulder Dash!
Bugs!
Cadaver - The Last Supper
Canal X II
Chamber
Championship Manager 93 [includes '94 data]
Classic Invaders
Czphonix
Dark Pearl
Deluxe SlideShow
Demo-Breaker: Dark Side Of The Spoon
DGDB
Diamond Format
Douglas Rockmoor 2
Dream Demo - Marlon Screen 2
Drop Down Words
Escape (Jag Jaeger)
Evil Rampage
Face Off (Krisalis)
Fexthor
Fighter Bomber
Flashback (Delphine Software)
French LinkWord
G-Force Menus List
Game Boy emulator
Generation
German LinkWord
Gone To The Dogs
Head Power
Hooray For Henrietta
Hoyle
Indiana Jones And The Fate of Atlantis (Adventure)
International Soccer Manager
Invertix
Ishido - Way Of The Stones
Jewel!
Jigsaw
Jigspell
Kidgraph
Kidgrid2
Kidmusic
Kidpublisher
Labo
Labyrint
Landscape Generator
Life
List Construction Set Run Only
M Demo 4
Maps And Legends - The Cartographer
Masterquiz I
Mec Love Story
Mega Funky Screen Flipper!
Mega Maths
Mercenary II - Damocles Mission Disk 1
Miami Chase
Minter 3.5k
Mod Mania volume IV
Moon Letters
Muzak Demo I
Neverending Tale
New Year Demo
Number Fun 1
Othello (Francois Villeneuve)
Passwords Show
Picture Mix 6+
Picture Puzzle (Mark Wickham)
Pipe Panic
Polar-Icze
Pools - Expert Results Predictor
Populous data disk 2 - Final Frontier
Power Basic Compiler
Premier League Manager
Premiere
Premium Mah Jongg
Primary Maths Course
Prince of the Yolkfolk
Protonz
Quick Index
Racetest!
Reaction
Reaction II
Reactor
Red Zone
Regles Grammaticales Espagnoles
Removsym
Reverse
Ripped Off Demo CD #118
Robot Attack
Robot Words
Russian LinkWord
Saddam Shoot! II
Scorched Earth
Sensible Soccer - 1992-1993 Edition
Serious Software Pack
Shadow Of The Beast III
Shoot Range
Silly Spirograph Generator
Sim City Custom Terraformer/Cheater
Skidpan
Slaytanic Cult Music Demo 2
Soko Ban
Space Harrier - 20 Levels Edition
Spanish LinkWord
Speccy Games
Spellbound Dizzy
ST Coloring Book
Star Raiders II
Starnukers
Start Arcade
STOS Solitaire Owl
The Aquatic Games
The Card Maker
The Computer Guide to the Solar System
The Elven Crystals
The FMC-Connexion Fullshow
The Kristal
The Silly Games Pack
The Space War
The Tipster
Things To Do With Words
Top Trainer
Traffic Jam Ahead
Train Set
Troddlers
Twinz
Universal Pictures
Wargame Phone Dialer
Wheels Of Fortune
Willy-Nilly
Word Race
Zmodem Receive
```

For some we will have a game page and we can link it, for some maybe not so we can either leave them as-is, or create a new game page.

**Comment by nguillaumin** [comment]
Found 51 that match a game based on the name (there are some duplicates unfortunately):

![names](https://user-images.githubusercontent.com/762512/232231102-68fd484f-47a9-4970-8f3e-adeb38e75bd2.png)

**Comment by MugUK** [comment]
Is there any fixes that I can do to take the weight off what looks to be an odious task of manually fixing them. Or do you have the database wizardry to do this (semi-) automatically?

**Comment by nguillaumin** [comment]
Unfortunately I can't think of a simple way to do it in the DB :disappointed: I made a few improvements in the Software screens in CPANEL to make the manual task easier and I recorded a video to explain it.

We can split the list in 2 if you want, I take from "All blocked up" until "Kidmusic" included and you take the rest?

[output.webm](https://user-images.githubusercontent.com/762512/232305878-ca1566bd-ddb1-4da1-986b-7a778d998062.webm)

**Comment by MugUK** [comment]
I'll take a look tomorrow when it's a bit quiet in work :)

Also want to get all the Serenade scrolltexts uploaded too as only got to 23 so far. (All text is ripped, just need to upload the contents)

**Comment by nguillaumin** [comment]
Ok, I made some progress, I have crossed out the ones I did in my previous table. I'll almost done in fact so I'm happy to do them all this week.

**Comment by MugUK** [comment]
Oh, OK. It saves me breaking anything. I'll go back to ripping/uploading scrolltexts :)

**Comment by MugUK** [comment]
All of Serenade's menu scrolltexts (where present) have been uploaded to AL now.

**Comment by nguillaumin** [comment]
Ok I fixed them all for the ones. We still are left with 92 software of type "games" that we should look into (as we probably have a proper game page for these) but that will be for another day.
