### ISSUE TITLE
Soccer Manager Simulator not displaying screenshots properly

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#217]
https://www.atarilegend.com/games/soccer-management-simulator-serious-games
![2023-04-14](https://user-images.githubusercontent.com/17252699/232146431-1b186056-1eba-481c-ae66-19399efd450e.png)

**Comment by nguillaumin** [comment]
The files are missing on the server. I checked old backups but could not find them so they seem to have been missing for a long time.

I took some new screenshots and uploaded them.
