### ISSUE TITLE
MAIN SITE - LAYOUT - Blurry pictures

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#222]
On the Game Details Page, the pictures are resized. So they appear blurry because of the browser processing.

We could use this kind of line in the CSS part:
```
<style>
img {image-rendering: pixelated;}
</style>
```

It should work with Chrome (tested), Opera (tested) and Safari (untested). Unfortunately, it's not yet supported by Firefox nor Microsoft Edge.

Trying to solve this issue atm.

How it is displayed
![wings of death 01](https://user-images.githubusercontent.com/12120244/29137731-a20b6392-7d41-11e7-82b3-ba7aaed1221c.png)

How it should be displayed
![wings of death 02](https://user-images.githubusercontent.com/12120244/29137730-a2062684-7d41-11e7-9816-445a985fa391.png)

**Comment by Brume-AL** [comment]
looks like the CSS {image-rendering: pixelated} isn't supported by Firefox in the latest version.

Have tried with this CSS and it seems to work fine:

<style>
img {image-rendering: crisp-edges;}
</style>

Let me know if that's OK for you, guys. Thanks in advance.

**Comment by nguillaumin** [comment]
This is done on the DEV server, let me know if it works for you. You may have to clear your cache as the CSS is not refreshed automatically (yet).

**Comment by Brume-AL** [comment]
Thanks, that works like a charm for me. Maybe could we add it to the "similar game" box, too?
See an example here:
http://dev.stonish.net/games/games_detail.php?game_id=2261
The captures of Mortville Manor are pixelated (which is perfect), but the screenshoot of Maupiti Island is blurry.
What do you think?

**Comment by Brume-AL** [comment]
Sorry, have answered too fast. The new CSS works fine with Firefox, but now the captures with Microsoft Edge or Chrome are blurry...

**Comment by nguillaumin** [comment]
Hm, I'm not sure how to handle that. We would need a different CSS for each browser I guess? Tricky...

**Comment by Brume-AL** [comment]
Yes, if you try to add the previous code img `{image-rendering: pixelated;}`, it will works.

I didn't find any doc about this issue. According to Mozilla, `crisp-edges` should work with Edge and Chrome, but this page hasn't been updated since 2019.
https://developer.mozilla.org/fr/docs/Web/CSS/Image-rendering

I guess it has been removed since then.

**Comment by Brume-AL** [comment]
Sorry to say, but pictures are still blurry with Firefox.

**Comment by nguillaumin** [comment]
The deployment to production failed, should be good now (you may have to clear your cache)

**Comment by Brume-AL** [comment]
Thank you, it works perfectly now!
Happy to see "real" screenshoots on the site 👍
