### ISSUE TITLE
Approving submissions (e.g. box scans)

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#223]
BelgarathUK has uploaded box scans for 3 x games (RVF Honda, Striker Manager and X-Out).

I've reviewed these submissions so that marks them as OK. But how do I make sure they appear on each page for these games? 

We obviously display box scans but how is it switched on after someone has submitted them?

**Comment by nguillaumin** [comment]
There's no automated mechanism to add them to the box scans of the game, so you need to download the images and add them yourself in the CPANEL.

Currently there's only an automated option to convert the submission to a comment, when relevant.

**Comment by MugUK** [comment]
Not completed as yet. Where is the option to upload a box scan as I can't find it. If it's there, then I'm going blind and I will book a new eye test :)  E.g. Oids has one, but in New or Legacy Cpanel, I cannot find a function that says "upload a boxscan".

**Comment by nguillaumin** [comment]
You have to pick a specific release first (since scans are specific to releases as they might have different boxes). Then on the left menu there's a "scans" section.

**Comment by MugUK** [comment]
That's the step I was missing. D'oh! RVF Honda now has box scans. I will do all the others that he has submitted.

(Unless you're thinking of doing a "Associate submission image with game x by clicking this button here" function???? :)

**Comment by MugUK** [comment]
Apologies for my next daft question, but it's also from a Submission. 

There's a request to add a Lemon Amiga link ((https://www.lemonamiga.com/games/details.php?id=4633) to the game Sardonic (https://www.atarilegend.com/games/sardonic). 

I've never done one of these before and I can't seem to find where these are added to the game's info in the database.

**Comment by nguillaumin** [comment]
Ahem... It seems there's no option to do so! Neither in the legacy CPANEL. Probably this data was imported once a long time ago and never touched. I will have to implement it. I will create a ticket for this.
