### ISSUE TITLE
Server Error when uploading scans

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#224]
I've tried to upload some fresh box scans this evening and if I do them as one-at-a-time, I get a server.

If I do them as two (front & back), then only the back is accepted and the front causes the same error.

This has happened with Hacker, Knightmare and Lure Of The Temptress. (The two-at-a-time problem happened with Hacker and Knightmare, so only the backs are uploaded). With LotTemptress I tried the front only and it failed. I then tried the back only and it failed again.

No idea why it's doing this as previous box scans have uploaded OK.

**Comment by MugUK** [comment]
I wonder if there are limits on the file sizes allowed?

   Bytes              Game
=====================
  4254348	Graffiti Man - Back (Uploaded OK)
  3409853	Graffiti Man - Front  (Uploaded OK)
  3124293	Hacker - Back  (Uploaded OK)
  5209716	Hacker - Front
  4527096	Knightmare - Back (Uploaded OK)
  5011237	Knightmare - Front
 11136316	Lure Of The Tempress - Back
 10302141	Lure Of The Tempress - Front

**Comment by nguillaumin** [comment]
@MugUK Could you post here one of the failing image?

**Comment by MugUK** [comment]
![Hacker - Front](https://github.com/atari-legend/atari-legend/assets/17252699/b2e5c273-ff98-4bab-8854-3436d24630d4)

![Knightmare - Front](https://github.com/atari-legend/atari-legend/assets/17252699/d00bbf40-60b1-473f-b4a2-26824e975bcb)

**Comment by MugUK** [comment]
I can resize them down a bit if that's the fix, but will need to know the exact maximum dimensions that the AL uploader can handle.

**Comment by MugUK** [comment]
I've just uploaded Dark Castle (Back) and both Front & Back for Hyperdome without any issues.

Filesizes (if that is linked to the upload problems) are:

Dark Castle (Back) - 289,480 bytes
Hyperdome (Front) - 168,349 bytes
Hyperdome (Back) - 265,913 bytes

These ones by Belgarath are *a lot* smaller than the ones that Total Eclipse submitted.

**Comment by stgraveyard** [comment]
Awesome, thanks for all the hard work, Mike.

**Comment by nguillaumin** [comment]
Thanks for providing the examples. I can reproduce the issue. When the files are over 5MB it switches to "chunk mode" to upload in chunks rather than one single upload, and something is not working there but I did not figure out what yet.

**Comment by nguillaumin** [comment]
I have disabled chunking, which fixed the issue. That will probably not work well with very large files, but we don't want these anyway.

**Comment by MugUK** [comment]
OK. There are some more submissions to wade through but at some point over the last weekend I tried to log in from my parent's house and my AL id just won't let me back in.

Can someone reset it for me so that I can change the pw (again) :)
