### ISSUE TITLE
Add CPANEL screen to add LemonAmiga / Lemon64 links

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#225]
Currently there's no way to add a link to LemonAmiga / Lemon64 in the CPANEL.

**Comment by MugUK** [comment]
So it wasn't me going loopy then (for a change) :)

**Comment by nguillaumin** [comment]
I have added a new section when editing a game, at the bottom:

![image](https://github.com/atari-legend/atari-legend/assets/762512/374f1e5b-e7fe-4da7-9fdf-520aa1278e95)

**Comment by stgraveyard** [comment]
Beautiful work Nico. Thanks so much.

**Comment by MugUK** [comment]
OK I will add that one submission tomorrow that we have.
