### ISSUE TITLE
Someone has submitted full maps to Ozone... how to store them.

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#226]
SToS  (Atari Forum user ID) has submitted every single level of Ozone in a single submission.

There are 12 level maps which I have to assume are numbered left to right per row. I need to check with him which ones are for each level - maybe he could add a small text bar under each one to confirm the level number and a little credit to himself and resubmit?

The big question is how best (and where) can we store them? They would work in Game Facts but I'm up for any other suggestions.

**Comment by stgraveyard** [comment]
Hi Mike,

I have done this for a few games with maps provided by AtariCrypt. I added them in the FACTS section. See as an example the game Prehistorik : https://www.atarilegend.com/games/prehistorik

I think it looks pretty good. 

Cheers,
Maarten

**Comment by MugUK** [comment]
OK. Do I assume that the order they are shown in Submissions is the same order for the levels? Or is there a way we can send a message to someone who's submitted something?

**Comment by nguillaumin** [comment]
Yes I think Game Facts are the most appropriate way currently.

For the order, we have to rely on what was submitted. To contact them, you can find their email address in the "User" section of CPANEL, there's no built-in messaging system.
