### ISSUE TITLE
Can't edit a game from AL pen icon - long error message pops up. Linked to Lemon Versus changes?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#227]
Unknown sub-section 'Vs'. Only AKA, Box back, Box front, Comment, Creator, Developer, Fact, File, Mag score, Music, Game, Publisher, Review, Review comment, Screenshot, Similar, Submission, Year, Release, Sound hardware, Video are supported for Games

**Comment by nguillaumin** [comment]
Well spotted. Unfortunately easy to forget possible impacts on the old CPANEL. I have fixed it. I will also change the pen icon to point to the new CPANEL, I think it covers most if not all the game editing function of the old one.

**Comment by nguillaumin** [comment]
Hm unfortunately the build of the legacy site is not working anymore so I could not deploy the fix. I did not find a quick fix for this, I'll need to spend more time on it...

**Comment by nguillaumin** [comment]
I have added screens in the new CPANEL to edit Facts, so you can use that for Ozone now 😃

**Comment by MugUK** [comment]
Cheers - I'll get those added later on today.

**Comment by MugUK** [comment]
Ozone maps added now.
