### ISSUE TITLE
Registration problems

### ISSUE THREAD

**Issue by bee8bit** [atari-legend/atari-legend#228]
Hi!

I had some difficulties registering as a new user. I have filled out the registration form on a computer ("A") where I cannot access my emails. So, I have received the verification email on a different computer ("B").

Clicking the verification link on computer B only takes me to a login form, possibly because that is not where I had begun the registration. Login was not possible, the response was "These credentials do not match our records.".

Typing the long link into computer A was also unsuccessful. I cannot tell, if I have mistyped any character of those long hashes, or if the link already had expired or if it was already used up by clicking the link on computer B.

Re-registering from computer B was not possible either, because my username and email address were already taken.

I could eventually resolve it by using the "forgot password" function and then requesting another validation email, all on computer B, but this was quite a cumbersome experience.

**Comment by nguillaumin** [comment]
Thanks for reporting this with all the details to reproduce it. There was indeed some confusion between the email verification process, and a user being marked active/inactive. I fixed it.
