### ISSUE TITLE
A way to extract Commercial titles without front/back scans?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#230]
Is this something that you could do Nico? I could post it in Atari Forum and Reddit/AtariST - but only after I've searched online for the easier ones to find :)

CSV file would be easiest for me as I can then expand it into Excel/Google Sheets for updating?

**Comment by nguillaumin** [comment]
I had a look, I think that would be the SQL query to use:

```sql
SELECT
    *
FROM
    `game`
LEFT JOIN game_release ON game_release.game_id = game.game_id
LEFT JOIN game_release_scan ON game_release_scan.game_release_id = game_release.id
WHERE NOT
    EXISTS(
    SELECT
        *
    FROM
        game_release
    WHERE
        game_release.game_id = game.game_id AND EXISTS(
        SELECT
            *
        FROM
            game_release_scan
        WHERE
            game_release_scan.game_release_id = game_release.id
    )
) AND game_release.license = 'Commercial';
```

Returns ~2100 rows, CSV below. I think I will try to integrate it in CPANEL somehow so that we can use it to fill in missing scans over time.

[game.csv](https://github.com/atari-legend/atari-legend/files/15049082/game.csv)

**Comment by nguillaumin** [comment]
I have added a card in the "issues" section that lists commercial releases that are missing a scan. Note that it's a bit different from the above because there might be games that have multiple commercial releases (e.g. 1 in France, 1 in the UK) but we only have scans for the UK one. But I think it's a bit more valuable if we want to try to complete missing scans.

![image](https://github.com/atari-legend/atari-legend/assets/762512/635551bd-bcad-44d9-8099-3e6bc9298b44)

**Comment by MugUK** [comment]
Sorry for taking so long to reply Nico.

I've downloaded the CSV and I will make a start on trying to find / upload box scans. Even if it's just a front scan, it's better than showing nothing.

**Comment by MugUK** [comment]
Done about 30-40 this afternoon. A few oddities either couldn't be found at all (not on MobyGames, Launchbox or GameFAQs) so some were "borrowed" from AtariMania. A strange one is Super Hang-On - I can't find the box front for the ST version, but only the box back scan. It's a start at least :)

**Comment by MugUK** [comment]
Still continuing with this when spare time allows. I've noticed quite a few PD titles on the list, which obviously will never have a front/back scan. Any chance of doing the export list with the PD titles removed?

E.g. Alien Thing

Or are they miscategorised in the database and need to be made Commercial PD titles?
