### ISSUE TITLE
Website has lower scrollbar in 1080*1920

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#231]
HI Nico,

Seems something changed on the webiste : 

![image](https://github.com/atari-legend/atari-legend/assets/4339294/71abfae6-113e-45aa-82a1-0af655e026c6)

I'm now having a lower scrollbar on the main page.

not the case on the old cpanel : 

![image](https://github.com/atari-legend/atari-legend/assets/4339294/38a9f58e-a171-4106-804e-0ac51938f6f5)

Any idea?

Maarten

**Comment by nguillaumin** [comment]
Yes, I see it too. Weird, I did not touch the main site in a long time (only CPANEL), so I don't know what is causing this...

**Comment by nguillaumin** [comment]
I fixed it I think. However I could not avoid small margins on the left and the right in the main content area:

![image](https://github.com/user-attachments/assets/193b3e6d-861f-41fd-9f43-b9f862e232ed)

But I think that's better than a scrollbar...

**Comment by stgraveyard** [comment]
great news. Thanks.
