### ISSUE TITLE
500 Server Error when uploading 2 x JPGs for Baby Jo? 

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#232]
Getting the above error when I try to upload a Front & Back scan for Baby Jo.

The files aren't huge by any means (both similar sizes at 800x700) and aren't large in filesize either.

I've been uploading a few more covers this afternoon without any errors at all.

Images are attached.
![Baby Jo (Back)](https://github.com/atari-legend/atari-legend/assets/17252699/66082993-e5ed-4328-ad06-876a4d4ca0af)
![Baby Jo (Front)](https://github.com/atari-legend/atari-legend/assets/17252699/05326e2f-046c-4bab-9e65-46e39812127f)

**Comment by MugUK** [comment]
I've just done Bad Cat and AV-8B Harrier Assault after attempting Baby Jo and both worked fine without the server error.

**Comment by nguillaumin** [comment]
Ah, it's a very stupid thing but the file extension is `jpeg`, and only `jpg` works. You can rename them as a workaround, but I'll try to get it fixed.

**Comment by MugUK** [comment]
I'm an idiot. Will rename and upload.

But if you're going to be changing any code, do you parse the filename at all?  I.e. if it says Front or Back? If so, how difficult would it be to change the buttons to Front or Back in the drop-down options, if those words are found in the filename?

**Comment by nguillaumin** [comment]
I fixed it.

> But if you're going to be changing any code, do you parse the filename at all? I.e. if it says Front or Back? If so, how difficult would it be to change the buttons to Front or Back in the drop-down options, if those words are found in the filename?

I don't parse the filename per se, it's just that the DB had a constraint to only allow `png` and `jpg`. But that's a good idea! You could create a separate issue for that? Thanks!
