### ISSUE TITLE
Parse filenames of uploaded covers so that Front & Back are auto-recognised

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#233]
When uploading lots of covers, it's an additional few clicks to sort out which ones are backs and which are fronts.

Can you add some kind of filename parser that auto-changes the option to Back or Front if those words are found in the filename(s)?

**Comment by nguillaumin** [comment]
Done! Thanks for the suggestion.

**Comment by MugUK** [comment]
Working great so far
