### ISSUE TITLE
Possible to move images from one release to the other?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#234]
I've found (by example) that Cadaver had both the original scans and the Kixx scans inside the same Release.

So I saved off the Kixx ones, deleted them from the original release. Then re-uploaded them into the database but under the Kixx release where they should be.

Is there an easier way to do this? Or can we maybe create a "move image to other release" function?

Also, as another possible situation, where disks scans are inside the Releases entry, when they should be in the Media entry? Like the Wings of Death (Thalion) entry.

**Comment by nguillaumin** [comment]
Yes, I think some edge cases were left over when we moved the box scans from the game level to the release one. In some cases we didn't know which release to assign and the wrong one got picked.

I would tend to think it's a rare case, so not worth implementing a transfer functionality? But let me know if you see it differently.

**Comment by MugUK** [comment]
I've been going through an extra large set of Boxscans from archive.org and finding a few missing ones to upload and that's how I found the above examples.

If there's not many, then I'll just fix as and when I find them.

**Comment by nguillaumin** [comment]
Ok, then closing this for now.
