### ISSUE TITLE
Adding a re-release/fixed versions of STAC adventures

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#236]
Thanks to Zippy making his STAC Decrypter last year, and thanks to Gons45 on the Atari Forum, there are some fixed versions of some STAC games that were broken.

However, when I try to add a new release to via the Games part, by adding 2024 to the new release and putting (Fixed) after the game's name .. the Save function doesn't generate a new Release in the database. It did it a few times with Phantom Zone, but eventually I was allowed to get the new fixed version added.

But Treasure of the New Kingdom (https://www.atarilegend.com/admin/games/games/4938) is refusing to let me add a new Release to it :(

Am I missing a step out of the process that I've forgotten about?  Create a new release, with changed details inc. year, then add the download via the Dump/Media option?

**Comment by nguillaumin** [comment]
There was a bug, in fact two:
- When there was an error with the publisher, it was not shown on the screen
- The publisher was set to be mandatory, where it shouldn't be

So you probably did not set a publisher on this release, which triggered a "mandatory" error, which was not visible...

Should be fixed now.
