### ISSUE TITLE
Can't remove undated entry from PileUp

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#237]
Moa has been sending in some Submissions so I've made a start on adding them to the database.

However, my first attempt causes a 500 Server Error.

He's sent in the year for PileUP (https://www.atarilegend.com/admin/games/4049/releases) but I couldn't edit the existing Release details. So I created a new release and put in the correct year. But I can't remove the older one. If I attempt to delete it, I get the above error.

**Comment by nguillaumin** [comment]
@MugUK Can you elaborate on this:

> I couldn't edit the existing Release details

It should work when you click on the release, and then pick a release year for example.

![image](https://github.com/user-attachments/assets/fb22569f-df67-4626-abc3-017ec62036b6)

Do you get an error when doing this?

> If I attempt to delete it, I get the above error.

That's right, I never implemented release deletion it would seem! Should be fixed now.
