### ISSUE TITLE
Main - Bug - News section - Data got corrupted?

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#58]
Hi Nico,

It seems we have finally lost some data. These news sections are really weird : 

![image](https://user-images.githubusercontent.com/4339294/101261534-5b09d780-3738-11eb-9441-cba74d3b99d3.png)

And this on page 2 : 

![image](https://user-images.githubusercontent.com/4339294/101261570-ae7c2580-3738-11eb-8799-a58f900e5d73.png)

I never wrote these things, they don't make sense at all...

Cheers.

**Comment by stgraveyard** [comment]
![image](https://user-images.githubusercontent.com/4339294/101261620-f1d69400-3738-11eb-87d4-bce4b8e9f157.png)

Data seems gone...

**Comment by stgraveyard** [comment]
I think we have to re-upload the complete news table : 

![image](https://user-images.githubusercontent.com/4339294/101265488-3e28d080-3747-11eb-8328-4b930a995b48.png)

Perhaps something went wrong with the conversion to the new link types?

**Comment by nguillaumin** [comment]
Yes, the script to convert to new links mangled some of the data. Bad regular expressions...

I restored a backup and fixed the scripts and now it looks good I think, please re-check and let me know if you see other problems.

**Comment by stgraveyard** [comment]
Nico, looks perfect now. Thank you. I will be making a nice anounce today.

Just one more question. Do you have any idea if this conversion issue could have had an effect on the reviews, interviews, articles ... ? That would kill me :-) When was this conversion done? I still have backups so nothing is lost ...

**Comment by nguillaumin** [comment]
Yes it could have as all content was processed. I restored a full backup though (not just news) so it should be ok. I checked some interviews / reviews / articles and they look ok but maybe do another check as you know the content better than me.

The conversion happened yesterday when I made the proto live so I was able to restore a backup from yesterday.

**Comment by stgraveyard** [comment]
Sounds perfect Nico.
