### ISSUE TITLE
Main site - Layout - User drop down

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#60]
Nico,

Sorry for being anal again about these things but just a question. Was this done on purpose? The fact that the log out button is a bit more lower : 

![image](https://user-images.githubusercontent.com/4339294/101286045-b4314400-37e8-11eb-8d3a-850c8d5c9f47.png)

Almost looks like an alignment issue. 

Maarten

**Comment by nguillaumin** [comment]
Hi, yes it's on purpose :wink: I thought we may have other links in there and it would be good to separate logging out. I also clicked a log on "Log out" by mistake when trying to click on "Control panel".

**Comment by stgraveyard** [comment]
Ok perfect! good thinking.
