### ISSUE TITLE
Main site - Bug - Articles link seems broken

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#61]
Hi Nico,

When pressing the articles button, the link now seems broken : 

![image](https://user-images.githubusercontent.com/4339294/101289007-ea2af400-37f9-11eb-9d5f-a6eeb020339e.png)

Cheers.

**Comment by stgraveyard** [comment]
OK, seems weird. When I add a new article which is not complete, the link gets broken. I will add a new article on dev first...

**Comment by nguillaumin** [comment]
I think I fixed it. It crashed if the article had no type, or no screenshots, which would have been the case for new ones.
