### ISSUE TITLE
CPANEL - Bug - Review section - Review detail

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#63]
Hi Nico,

I know you are thinking of or working on a new CPANEL (yipeekayay!!!) so I don't know if I should mention these bugs? 
Anyway, when wanting to look through a review (legacy.atarilegend.com) I'm getting this : 

![image](https://user-images.githubusercontent.com/4339294/101980683-6f356380-3c67-11eb-8b8e-0812cd565461.png)

(This is for the BADLANDS review - Same happens for the Addams Family review)

When checking Arkanoid 2, all seems ok : 

![image](https://user-images.githubusercontent.com/4339294/101980716-adcb1e00-3c67-11eb-9e97-bc4165f46e95.png)

Seems like a new little bug ... I think this happens for screenshots that don't have a comment with them.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks, makes sense to keep fixing the existing CPANEL I think.

It was a bug when a screenshot had no comments. Should be fixed now.

**Comment by stgraveyard** [comment]
Perfect.
