### ISSUE TITLE
Review, Articles, Interviews - Offline flag

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#64]
Hello Nico,

Currently, I have noticed on the DEV server you have implmented the first tests of the new CPANEL, this means I can not use this server for new interviews, reviews and articles. When I add one of these on prod they immediately are online. 

Normally I work on these things for a few days, have them spellchecked by Mike, do translations and so on ... So as discussed, it would be really neat to have a 'putt offline' flag in the CPANEL parts of these sections. This way, we can flag it and when this flag is active, the interview or article or review is not yet displayed on the main site and we have time to nicely finish it. 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I have implemented this. There's now a DRAFT label for draft content, and a checkbox to switch between draft / published:

![1](https://user-images.githubusercontent.com/762512/102012533-53a38900-3d4b-11eb-9db3-a64eb9594e12.png)

![2](https://user-images.githubusercontent.com/762512/102012534-556d4c80-3d4b-11eb-9d79-dd2142bf80fe.png)

 it's deployed on the dev site, please have a look and if it's good I'll deploy it to prod.

**Comment by stgraveyard** [comment]
Nico, 

Are you talking about dev.atarilegend.com? Because the cpanel link doesn't work when I use the profile button and when I go directly to dev.atarilegen.com/admin I'm seeing a new version of cpanel : 

![image](https://user-images.githubusercontent.com/4339294/102138809-3ced5700-3e5d-11eb-8e78-d647d945454c.png)

**Comment by nguillaumin** [comment]
Yes, you have to manually log in to the legacy CPANEL. dev.atarilegend.com CPANEL link takes you to legacydev.atarilegend.com where you have to log in (same as www.atarilegend.com -> legacy.atarilegend.com where you have to log in as well).

I plan to make that clearer in the future by only keeping the login form on the legacy site and remove all of the "main" pages.

**Comment by nguillaumin** [comment]
So I found out why that was confusing, there was a redirect to the "previous" URL meaning that if you were not already logged in to CPANEL you would get back to the main site, but without any message or anything.

I have changed the legacy site so that only the login form is visible now. So if you click on the CPANEL link from the new site and you're not already logged in CPANEL, you will get a login form.

Please give it another go @stgraveyard !

**Comment by stgraveyard** [comment]
Hi Nico,

Sorry for the long wait. I have tested this and it is working like a charm. BUT, I have one final little suggestion. It is no obligation ofcourse, but if you create a review, interview or article, can you make it so it is created as 'draft'? Now when you create an interview, you have to set it in draft and update it. 

This is just a minor thing and again, it works as it is now...

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Of course! That makes complete sense. :+1: I have made the change, please have a look.

**Comment by stgraveyard** [comment]
Hi Nico,

When creating a review , now the flag is indeed active, but look how the screen is displayed : 

![image](https://user-images.githubusercontent.com/4339294/103044472-eed50380-4580-11eb-94bc-5a1786f2e687.png)

For the other sections is displayed correctly and working properly.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
This is an old bug actually, unrelated to the drafts. It happens on prod as well. It's when the game being reviewed has no screenshots, the DIVs were unbalanced. I fixed it.

**Comment by nguillaumin** [comment]
This is now deployed on prod.

**Comment by stgraveyard** [comment]
Ah cool. Another bug fixed. Thanks.
