### ISSUE TITLE
Menus database structure

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#65]
Hi, I started to work on the menu database structure. I looked at we already have in the database, as well as the Stonish database tables. Here's what I came up with:

![al-menus-v1](https://user-images.githubusercontent.com/762512/102716158-51f13c80-42da-11eb-8f6a-8bdc0de9808b.png)

I need your input to validate the schema, especially Brume-AL with his experience on Stonish.

A few things of note and that may differ from the Stonish structure:
- The top level structure is the "menu set", for example "Pompey Pirates" or "Krappy Compacts"
- A menu set can be made by multiple crews
  - Is it really the case, or is there only always 1 crew?
  - Stonish has the concept of "alliances" it looks like, but it doesn't seem to be used?
- A menu set has multiple "menus". A menu is the actual menu like "Pompey Pirates 42"
  - This did not exist on Stonish or AL DB, there was directly the menu disks. However I think it makes sense because the "version" is tied to a menu, not a disk, as well as the menu number
- A menu has multiple "menu disk"
  - A disk has a number as well, but also a "part" which can be used when it's part A, B, C, or sometimes "Part II", "Part III", etc.
- A disk has multiple dumps, similar to the dumps for games
  - The dumps are what's donated, not the menu disk directly (This is a change from Stonish)
- A menu disk is linked to multiple "content", the actual software
  - The content can be linked to an AL game (not a release), or a DemoZoo production
  - There's also a "name" field in case it's not a game or a production
  - And also a content type (e.g. doc, music, tool, game, ...)

Some open questions:
1. As above, can there be multiple crews for a menu set?
2. Does it make sense to link to an AL game rather than a release? On one hand yes because it will be very difficult to know exactly which release of a game has been cracked. On the other hand we could create a separate release for each game that is part of a menu? Maybe that makes more sense as it is indeed a separate release, with trainers, specific memory/system requirements, etc?
3. For who donated the dump, does it make sense to use the existing individual table, or we should have a separate "donators" table?
4. In the current AL schema there is also the link between a menu and individual (for example to say who did programming, music, graphics, etc.) like we do on games. I have not replicated it here as I think it's overkill, but should we do it? We could also do it later.
5. On Stonish there is a "requirements" column to say for example when a software has TOS or memory requirements. We already have this on the release, so maybe that's another argument to create releases for menus?

**Comment by stgraveyard** [comment]
Nico, before I start scratching my brain, have you checked out this excel : https://github.com/atari-legend/skins-and-docs/blob/master/Technical%20documentation/AL%20table%20analysis.xlsx

I know you were against it back then, but this thing contains a big analysis of the menu table section also with documentation and explanation, see the menu structure tab. 

Please have a look and come back to me. Sorry for being hasty, I just don't want us to redo all this work if not necessary as I/we already spent countless ours discussing this structure.  Have a look first.

**Comment by nguillaumin** [comment]
I was not against it, I just disliked the idea of putting an Excel file in the repo as it made it hard to collaborate (as opposite to Google Sheets for example), but I'm definitely in favor of documenting things! 👍 

I did look at it, well I did look at the existing DB schema, and as well as the "Tech Docs" section of the CPANEL which contains the same thing as the Excel I believe.

My structure is definitely inspired by this, as well as Stonish. But I did made changes that I thought sensible mostly to simplify things.

**Comment by stgraveyard** [comment]
Nico, just want to add that the excel is not the same as the tech doc. The excel really was the last version and a culmunation of all the discussions we had.

**Comment by nguillaumin** [comment]
In terms of the menu structure the Excel seem identical to the tech doc, no?

![menu-structure](https://user-images.githubusercontent.com/762512/102915928-ed251600-4482-11eb-9060-09c8ccbbac78.png)

Even the image of the schema seems to be the same.

But maybe I misunderstand and you mean something else?

**Comment by stgraveyard** [comment]
Yes, you are again correct. I thought you meant the old tech doc file. Sorry.

**Comment by stgraveyard** [comment]
Nico, I contacted Bruno, hope he can reply quickly. I am not really the person to answer these questions, all I can say is ... Wow, I'm looking forward to this!

**Comment by stsilversurfer** [comment]
> 2\. Does it make sense to link to an AL game rather than a release? On one hand yes because it will be very difficult to know exactly which release of a game has been cracked. On the other hand we could create a separate release for each game that is part of a menu? Maybe that makes more sense as it is indeed a separate release, with trainers, specific memory/system requirements, etc?

This is indeed a tricky part. We would like to view them as separate releases in my opinion as in many cases the games were altered in various ways (trainers etc). In some cases crews used cracks from other crews, this will mean that the same version of a game crack can show up on more then two menu sets

> * Stonish has the concept of "alliances" it looks like, but it doesn't seem to be used?

We have already implemented something similiar on AL although we don't use the word alliances but we can add both crews and individuals to crews.

![image](https://user-images.githubusercontent.com/11892803/103157841-8754c900-47b7-11eb-93ff-467797a39601.png)

**Comment by nguillaumin** [comment]
Hey @stsilversurfer , long time no see! Nice to see you here :smile: 

I agree about releases, the more I think of it the more it makes more sense than pointing to a game. Also thanks for the details about the crew genealogy!

I started to work on this including a tool to import the Stonish menus. That led me to revise the schema a little bit because on Stonish the field `letter` is sometimes used for a disk letter (e.g. Pompey Pirates 13 disk **A**) or a menu number (e.g. Mad Vision **B**). So now:
- Menus have a either a `number` (e.g. PP **13**)or an `issue` (e.g. Mad Vision **B**). They also have a version.
- Disks have a `part` which can be a letter (e.g. PP 13 disk **A**) or anything else.
- Added the standard `created_at`, `updated_at` Laravel fields

![schema](https://user-images.githubusercontent.com/762512/103243706-f28ad080-495a-11eb-9cf5-d85bb1c59062.png)

I managed to import all the data including screenshots and ZIPs, except for now the specific content (Link to release). Some manual correction may be necessary after the import but should be minimal. Probably around crew association, since a lot of Stonish crews are missing from Atari Legend, and also there's no separation between crew and menu set in Stonish (so I cannot know for example that "Pompey Pirates Krappy Kompact" is made by the crew "Pompey Pirates").

The initial open questions remain, and a few more:
1. Will we ever have more than one dump for a menu disk? If not that would simplify things a lot
2. Will we ever have more than one screenshot per menu disk?

And finally quick sneak peak of the new CPANEL screens (still work in progress):

![cpanel-1](https://user-images.githubusercontent.com/762512/103243906-9eccb700-495b-11eb-8e63-a2e68c97b5d0.png)

![cpanel-2](https://user-images.githubusercontent.com/762512/103243907-9eccb700-495b-11eb-94c4-e1d8da34425a.png)

![cpanel-3](https://user-images.githubusercontent.com/762512/103243909-9f654d80-495b-11eb-9ecd-efe87e1c6d5e.png)

**Comment by nguillaumin** [comment]
Here's how it look on the front-end currently (Strider first, then Dungeon Master):

![strider](https://user-images.githubusercontent.com/762512/103282718-ee9c9400-49d6-11eb-8d85-be01770ca065.jpg)

![2](https://user-images.githubusercontent.com/762512/103282720-f0feee00-49d6-11eb-8bc0-8f2ae746732e.png)

We probably need to think a bit about the presentation. Probably move these release into their own box, and don't display the date (since it will be missing for most). Also there are some duplicate-like because on Stonish some software is present twice for example Strider + Strider (doc). Unfortunately we can't easily distinguish both as "doc" is just a text column, not a type one (there is a type but in this case both Strider and Strider (doc) are typed "Game")

**Comment by Brume-AL** [comment]
I take the bandwagon.
At first, thanks for the work you've done on Stonish db, Nico!

But I really agree, we really need to discuss about the presentation. What kind of stuff want people when they visit a retrogaming website? Some information about their favorite games, but they also want to download them. 
Just my two cents, but the release box shouldn't be on the left nor the right side. This a very important box. On my side (Maarten will hate me ;) ), I'd prefer to see the box 'Reviews' on the left or the right. So the 'Releases' box has to be located on the middle, under the screenshots box. The debate is on, tell me what you think.

**Comment by Brume-AL** [comment]
>     1. As above, can there be multiple crews for a menu set?

Yes, that's possible. A few examples:
http://stonish.net/Fuzion-&-V8-216#st1
http://stonish.net/Hidden-&-Zuul-212#st1


>     3. For who donated the dump, does it make sense to use the existing individual table, or we should have a separate "donators" table?

You're right, we could use the same db as the existing table.

>     4. In the current AL schema there is also the link between a menu and individual (for example to say who did programming, music, graphics, etc.) like we do on games. I have not replicated it here as I think it's overkill, but should we do it? We could also do it later.

That's a huge work. D-Bug did it for Automation & their own menus, it took some years to finish it. I don't yet feel the courage to do this for Stonish's 3600 menus.

>     5. On Stonish there is a "requirements" column to say for example when a software has TOS or memory requirements. We already have this on the release, so maybe that's another argument to create releases for menus?

Yes, requirement on original games should be different compared to the cracked/menus versions.

**Comment by nguillaumin** [comment]
Thanks @Brume-AL . For the presentation let's keep it separate, I'll open another issue so that we can keep this one on the DB structure.

Thanks for the answers to the questions. 2 more from my previous comment:
1. Will we ever have more than one dump for a menu disk? I would say no because we already distinguish different versions of a menu (v1, v2, ...) and they have their own dumps
2. Will we ever have more than one screenshot per menu disk? I would say yes, even if we'll mostly have 1 screenshot it would be good to have the option to add more.

**Comment by Brume-AL** [comment]
> 
> 
> Thanks @Brume-AL . For the presentation let's keep it separate, I'll open another issue so that we can keep this one on the DB structure.
> 
> Thanks for the answers to the questions. 2 more from my previous comment:
> 
>     1. Will we ever have more than one dump for a menu disk? I would say no because we already distinguish different versions of a menu (v1, v2, ...) and they have their own dumps

No, a menu disk has one dump only in order to avoid duplicates. that's why I created Stonish. It might sound pretentious, but I wanted to create the ultimate base of menus without duplicates. TOSEC has tons of duplicate disks, with just one or two bits changing. Anyone can alter a disk by, for example, modifying the DESKTOP.INF file, changing the name of the .PRG in the AUTO directory, altering the high-scores, or even adding some bit in an empty place in the image-disk.

>     2. Will we ever have more than one screenshot per menu disk? I would say yes, even if we'll mostly have 1 screenshot it would be good to have the option to add more.

Yes, some menus could have many screenshots since they have two or more intros or "sub-intros".

**Comment by stgraveyard** [comment]
Hey all,

Great everybody is participating. 

I would like to throw some NOOB remarks in the group, maybe this can also trigger some ideas. 

1) Regarding the CPANEL *blown away* Only remark, Can we also switch to a black look, like the main site, or should I open my mind and go with something completely different like you are doing now? ;-)

2) The release box. I have some remarks. Nico, I noticed you have uploaded some disks, without info : 

![image](https://user-images.githubusercontent.com/4339294/103297928-932fcd80-49f9-11eb-9553-b598744a11b8.png)

So this one is linked to the Titus release of 1988. So is this disc the true original release? Or a hackl? 

I'm asking this because of the following. If it is a hack, or a single crack not from a menu, shouldn't we add some tiles as follows : 

- Official releases (containing the original and re-releases)
- Cracked versions (tile containing single cracks)
- Menu version (tile containin a link to THE MENU SECTION --> I suppose we will make a complete menu section, a bit of an intigrated STONISH, with a MENU button in the top bar)

And when you think about it, and when you think about what Bruno says about the fact that releases and menu's are important. What if the small tiles are just links to completely detailed menu and release sections? Currently, the release details are displayed in the game section, I think this is cool personally. But maybe we can make some kind of HACK section, so the CRACKED version tile is merely a link to the HACK section, and the menu version tile a link to the menu section. 

If this makes sense. Again, I'm not a specialist, just throwing some ideas in the wild ;-)

AWESOME WORK NICO!!!!

Cheers.

**Comment by nguillaumin** [comment]
Thanks @Brume-AL for the additional answers! :+1: 

@stgraveyard Yes I've been uploading some dumps to get a feel of how it works in practice. It's actually quite tedious with lots of clicks, I'd like to improve that (I have some ideas for automated mass importer, but we'll see later...).

I have uploaded official, non-hack versions. Cracked versions (not part of a menu) should be a separate release with the "Crew" set. So for example for Crazy Cars 2 you may have:
1. One official release by Titus
2. A single-crack version by some crew
3. Additional releases for each menu it's part of, for example one for Blue SoftWare 19, one for Pulsion 19, etc.

Does that make sense?

Regarding presentation please discuss on #77 to keep this issue focused on the structure, thanks!

**Comment by Brume-AL** [comment]
> Hi, I started to work on the menu database structure. I looked at we already have in the database, as well as the Stonish database tables. Here's what I came up with:

Something I forgot to mention. We need to specify the direction of the menu numbering. There was a crew who didn't make the things like the other. And guess what? They were French :)
Look here:
http://stonish.net/Euroswap-51#st1
I never found another team who reversed the numbering, so it was easier to use a small trick on Stonish. Something like that:
`if ($yourmenu == 51) {$TRIAGE = "DESC";}
else {$TRIAGE = "ASC";}`

then 

`ORDER BY name, issue $TRIAGE, letter, version, id_allmenus`

Where 51 is the ID of Euroswap.

Long time ago, we spoke about this case with Mattias & Maarten and they came to the conclusion this kind of information has to be integrated in the db instead of tricking the php code.

**Comment by nguillaumin** [comment]
Nice! :+1: Exactly why I was asking for your feedback to make sure we're not missing any of this :laughing: I have added a field " sort order", and during the import I set it to "descending" for Euroswap.

**Comment by nguillaumin** [comment]
I'm still working on this, I'm not completely happy yet with how the menu content are structure. As it is where a menu only has docs for a game (for example the Sewer Doc Disks) we still need a release to create a link in the content, which does not make sense (there's no release of the game on the menu). So I think we need both the ability to link to a release, and to a game from a menu.

**Comment by nguillaumin** [comment]
Another point has to do with non-game software, for which we don't have an entry in the AL DB. On Stonish there is a dedicated table for this, so that we can say "ProTracker appears on menu X, Y, Z". Currently I have not replicated this because it would mean maintaining a database of software in AL, next to the game (I still provide link to DemoZoo though when available).

Any thoughts of this? Do we want to be able to list all menus a specific non-game software is on?

**Comment by stgraveyard** [comment]
Hi Nico,

Sorry for replying so late.  Could we make a temp table, some kind of junk program table, so that we at least can display what is on the menu's? Without anything more. Does that make sense?

**Comment by nguillaumin** [comment]
Thanks, I think it wouldn't help. The problem is really how we store software information: Either just a name as a text, or in a separate table like Stonish. A separate table is safer otherwise a simple typo or whitespace in the name would give 2 different entries (for example "Pro Tracker" vs " Protracker"). So in the end I added a table, I think it's the only way to list all menus a non-game software appears on, like on Stonish:

![boulboot](https://user-images.githubusercontent.com/762512/105609416-7775d800-5da9-11eb-9919-c52ec71a2e9c.png)

**Comment by stgraveyard** [comment]
I would really love to test it out, because honestly, as a noob, I don't know what I'm looking at. 
What is Boulboot? And why is boulboot linked to DZ and all the other like 'lablemaker', 'Restart', 'MakeList' ... not? Where are those links leading to? Those are not games, so it seems?  And why is there an 'i' behind the games names? 

It does look cool though ....

**Comment by nguillaumin** [comment]
I'll put it on dev when it's ready and you'll have plenty of time to give feedback, I swear :smiley: 

I'll put your comment on the appearance on #81 so that we can keep this ticket on the DB structure.

**Comment by nguillaumin** [comment]
Closing this. I think the DB structure is good now.
