### ISSUE TITLE
Change log - Usercomments don't show up

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#66]
Nico,

I don't know what is going on but something is fishy. I have seen the user 'Stainless' added a user comment in the database: 

![image](https://user-images.githubusercontent.com/4339294/103044281-49219480-4580-11eb-9710-b71affca7ece.png)

This was on december 22. However, this is nowhere to be seen in the changelog. When we check december 22 we see this : 

![image](https://user-images.githubusercontent.com/4339294/103044328-69e9ea00-4580-11eb-9b63-2221c9eeead7.png)

Now, unless I'm dreaming, I would swear I had build this in. Now it shows a 'user' section update. I have this strange feeling a bug crept into this code? 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
The changelog for comment is not implemented in the new site, it's an oversight. I will add it.

The "Update" on the user is probably because the user changed something in their profile

**Comment by nguillaumin** [comment]
Ok that should work now. I have revamped the changelog system, I was trying to make it as automatic as possible but I can't find a good way, so we'll keep manually calling functions to add to the changelog wherever it's needed.
