### ISSUE TITLE
Top bar on main site not complete

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#67]
Nico,

It seems  the top is missing graphics? 

![image](https://user-images.githubusercontent.com/4339294/103077644-7433d480-45d0-11eb-9250-294a75b9da78.png)

What happened?

Maarten

**Comment by nguillaumin** [comment]
Yes, it's a CSS issue when I upgrade Bootstrap. I have already fixed it on DEV but just waiting on the draft stuff to be complete to deploy.

**Comment by nguillaumin** [comment]
Fix now deployed on prod.
