### ISSUE TITLE
Activity log - bug for submission and comment

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#68]
Hi Nico, 

I noticed this in the activity tile when editing a game : 

![image](https://user-images.githubusercontent.com/4339294/103150945-8309bb00-4779-11eb-94e6-895e61ed8c93.png)

Cheers.

**Comment by nguillaumin** [comment]
The activity log was missing code for some sections like Submissions and Comments. I added them and I also handled error betters so that we'll get a warning if something is missing next time. Deployment is in progress.

**Comment by stgraveyard** [comment]
Thanks a lot. This is a very important section for me. I check it a lot.
