### ISSUE TITLE
Article section - issue when adding screenshot

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#69]
Hi Nico,

Working on a new article (draft option works amazing!). When adding a screenshot without a comment, I'm getting a warning : 

![image](https://user-images.githubusercontent.com/4339294/103151096-42ab3c80-477b-11eb-8f24-a884a7d95751.png)

(this is on prod)

When I add a comment to the screenshot, the warning is gone. 

This does not block anything.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I could not reproduce exactly this but I think I fixed it nonetheless. Deployment is in progress.

**Comment by stgraveyard** [comment]
Seems indeed solved. Can't even read the php code anymore :D
