### ISSUE TITLE
One result in the search engine

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#70]
Hey Atari-friends :)

At first, the new version of the website is a brilliant work!
I specially like some new features such as the one which displays some games when adding an author in the games editor! Really useful!

OK, now let's speak about the first 'missing' feature. On the previous version, when we made a search of a game and when there's only one result, it opened the game page directly. Now the site displays a result of the search, even if there's one result.

See there for instance:
https://www.atarilegend.com/games/search?title=Alcatraz

Hope this can be solved easily.

Thanks in advance.

**Comment by nguillaumin** [comment]
Thanks! The display of some game next to the names was requested by Marcer actually :wink: 

I have fixed the bug for the search. I knew about it actually but I didn't like this feature too much (I'd rather always see search results) so I did not fix it :stuck_out_tongue: But I think it makes sense especially if we're "sure" this is the correct result by comparing the title entered by the user and the title of the game, they need to match exactly.

**Comment by Brume-AL** [comment]
Thanks, that's perfect 😉
We discussed about this feature with ST Graveyard a few years ago and we came to the conclusion it makes sense where there's only one result. Also considering the field to search a game uses autocompletion method, it reduces the number of pages displayed to reach a specific game.
