### ISSUE TITLE
CPANEL - BUG - Error on updating review

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#711]
Hi guys,
There's an issue with the screenshoots here:
https://www.atarilegend.com/games/games_reviews_detail.php?game_id=799&review_id=108
I tried to solve the bug in updating the review from the CPANEL, but it didn't work.
Thanks in advance for your help.

**Comment by nguillaumin** [comment]
I assume that got fixed, as it seems to work now.
