### ISSUE TITLE
Publisher isn't clickable anymore in the Releases section

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#73]
On the previous version, it was possible to click on the publisher to display all titles published by the company.

It isn't possible anymore. I know we can still use the search page to display this kind of information, but I really doubt most of the people will use it.

![image](https://user-images.githubusercontent.com/12120244/103155725-98dfa600-47a2-11eb-93cc-179e153f6aee.png)

**Comment by nguillaumin** [comment]
It's not clickable in the release list, however if you go to the release itself it is:

![3](https://user-images.githubusercontent.com/762512/103156133-e6a9dd80-47a5-11eb-8c0d-1c9fe4f0d8bf.png)

I'd rather keep it like that to avoid too many links in the release box, as it might become a bit confusing? But if it's important to you I can change it.
