### ISSUE TITLE
CPANEL - BUG - Error on updating a release

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#744]
Hello guys,

It's been a long time since I wrote here. Hope everyone is fine.

Just to let you know there's a bug since a few days on the CPanel. When we try to update or create a new release, we get the following message:

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in /homepages/23/d403148868/htdocs/php/vendor/pclzip/pclzip/pclzip.lib.php on line 190

The changes are OK, but the message appears on each modification.

Thanks in advance for your help.

Brume

**Comment by nguillaumin** [comment]
Fixed in the latest deployment.
