### ISSUE TITLE
Interviews - Screenshots without comments

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#75]
Hi Nico,

When adding a screenshot without a comment in the interview section, I'm getting the same error as in the article section :  

![image](https://user-images.githubusercontent.com/4339294/103173591-44006600-485c-11eb-8aeb-bcec7e668af8.png)

example : https://legacy.atarilegend.com/admin/interviews/interviews_edit.php?interview_id=48

This needs another quick fix ;-)

Cheers.

**Comment by nguillaumin** [comment]
Should be fixed now

**Comment by stgraveyard** [comment]
Nico, could you also add this fix to the review section? I bet it is also effected.

**Comment by nguillaumin** [comment]
I checked but it doesn't look like it, as you cannot add screenshots in a review (only use the existing screenshots of the game)

**Comment by stgraveyard** [comment]
Oh ofcourse. Sorry about that.
