### ISSUE TITLE
Search feature from game detail

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#76]
Hi Nico,

I found a little bug. The game is H.A.T.E developed by Vortex Software : 

![image](https://user-images.githubusercontent.com/4339294/103181417-0a058300-48a1-11eb-909d-2e88f701f45f.png)

When clicking Vortex I see this : 

![image](https://user-images.githubusercontent.com/4339294/103181442-53ee6900-48a1-11eb-9cab-258d4f9d14e6.png)

Game by CEREBRAL vortex are also displayed. This is because we search on name, not developer ID.

Cheers

**Comment by nguillaumin** [comment]
Ah yeah I implemented based on names initially because I did not have the search by ID yet on the search page.

Should be fixed now, also for Genres where the same thing was done.
