### ISSUE TITLE
Releases presentation

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#77]
We need to review / re-think how we present releases, especially as we'll add menus that will add a lot of releases to games.

@Brume-AL said:

> But I really agree, we really need to discuss about the presentation. What kind of stuff want people when they visit a retrogaming website? Some information about their favorite games, but they also want to download them.
Just my two cents, but the release box shouldn't be on the left nor the right side. This a very important box. On my side (Maarten will hate me ;) ), I'd prefer to see the box 'Reviews' on the left or the right. So the 'Releases' box has to be located on the middle, under the screenshots box. The debate is on, tell me what you think.

Also adding the quick mock-up with releases imported with the current presentation:

![](https://user-images.githubusercontent.com/762512/103282718-ee9c9400-49d6-11eb-8d85-be01770ca065.jpg)

**Comment by nguillaumin** [comment]
Personally I'd be ok to have the releases in the middle column. I agree it's an important information especially as it leads to downloads.

I also think we should separate official releases, from the ones coming from the menus. I would put the ones from the menus in a separate box and presented differently.

**Comment by Brume-AL** [comment]
First attempt with the releases box in the middle column.

![image](https://user-images.githubusercontent.com/12120244/103317988-377f3780-4a2d-11eb-8481-da1980ed3fff.png)

**Comment by nguillaumin** [comment]
Here's what I had in mind. I moved the reviews on the left like you, but presented the menu separately from the other releases:

![1](https://user-images.githubusercontent.com/762512/103558108-75a8ab00-4eb4-11eb-817a-2429dcd19fe0.jpg)

![2](https://user-images.githubusercontent.com/762512/103558111-76414180-4eb4-11eb-89cc-ef8deeaa63cc.jpg)

![3](https://user-images.githubusercontent.com/762512/103558112-76414180-4eb4-11eb-9109-78367951ec5c.jpg)

**Comment by Brume-AL** [comment]
This look very very good to me @nguillaumin !
Thanks for this brilliant work, I vote for it!
👍👍👍👍

Just a note: maybe it is not necessary to display the contents of each menu under each screenshot, I don't know.
When the content is long (more than 10 or 15 items), it makes very very long boxes which seem disproportionate to the others. 
Anyway, if I understood correctly, each menu will be clickable and will return to the page where we find all the menus, is that right? One this page, the full content of each menu will be displayed, isn't it?

**Comment by nguillaumin** [comment]
Thanks! Yes I agree with the contents sometimes it's too long. Maybe we can only display the first 5 entries with a "more..." link to see the rest.

Yes there will be a link pointing to the specific menu within the menu set, the other screenshot I shared. Then perhaps that's where the "more..." link should point to.

**Comment by stgraveyard** [comment]
I really really like the presentation of the menu disk in the game detail page! 

But why did you switch the review tile with the release tile? Let's take Turrican 2 for example : 

![image](https://user-images.githubusercontent.com/4339294/107879798-4c2f6600-6edb-11eb-8df6-5f9e8d2ba916.png)

I was wondering why you would put the releases in the middle (as this tile clearly would fit the small size of a side tile) and the review to the side? I think it would look much better like it was. 

ALSO, this is I think important for the whole team and visitors. The release tile contain official and unofficial release, but NOT menu disk releases. So I wonder if we should state this somewhere in the tile? 

Cheers.

**Comment by stgraveyard** [comment]
This is an example of the game detail page of the game Commando. 

![image](https://user-images.githubusercontent.com/4339294/107879955-2c4c7200-6edc-11eb-950a-ccecb821b5f3.png)

Although I really like the look, I have some doubts of the sentence in the red circle. Wouldn't it be better to have a tile with title MENUDISK RELEASES to stay in the same boat as the whole of the page?

**Comment by stgraveyard** [comment]
On the game detail pages, all the 'i' are missing from the menudisk titles, which is much better IMO : 

![image](https://user-images.githubusercontent.com/4339294/107880024-8e0cdc00-6edc-11eb-919c-afbb7e327484.png)

Compare this to the menu disk section : 

![image](https://user-images.githubusercontent.com/4339294/107880045-a67cf680-6edc-11eb-8435-2c45650a903f.png)

which lead to 'release pages' which seem useless to me.

**Comment by stgraveyard** [comment]
I have one remark regarding the responsiveness of this page. And I know this is really hard and if too difficult we will leave it as is. But when we go to 2 columns or 1 column, the order of the tiles doesn't make sense to me. As now, the menu disks come straight underneath the screenshots and the actuall game data below that. But it is not a big deal. 
On all other pages, responsiveness seems very good!

**Comment by nguillaumin** [comment]
The swap between the review / releases was discussed with @Brume-AL  (See first message of this thread) so I wanted to try it. The idea was that we could then display more information on each release because we have more space now, compared to being "cramped" on the left-hand side. But since we don't list the menu releases anymore, maybe it is not necessary?

For official / non-official releases I agree, initially I renamed the tile "Official releases" but it's wrong since there are also non-official ones (e.g. single cracks or others). So I don't know what title to use. "Non-menu releases" does not sound nice. Do you have any ideas?

The text "This game is also found..." I think I tried to put it in a box, but then it would mean a "box in a box" as all the menus would be in that box too and that did not look nice. I tried to change it to put just the text in a box, let me know what you think.

The missing ℹ️ on the game page: I removed them here to see and I agree it looks nicer. Problem is that there's no way to get to that release currently (except clicking on the menu first, and then on ℹ️). I don't know. Maybe we can just not have menu releases at all? But it would mean we could not document the specifics of that release (such as the trainers options, etc.)

Responsiveness: I agree a different order would be better. It's hard to achieve though. Let's keep that for last once everything else is sorted out.

**Comment by stgraveyard** [comment]
> The swap between the review / releases was discussed with @Brume-AL (See first message of this thread) so I wanted to try it. The idea was that we could then display more information on each release because we have more space now, compared to being "cramped" on the left-hand side. But since we don't list the menu releases anymore, maybe it is not necessary?
> 
Nico, yes please at least consider putting it back, I think it would look a lot nicer, especially on the games with a review and personally, I think the review section is still a very nice feature of AL and I like to give it a bit of special attention where we can. Just my 2 cents ...

> For official / non-official releases I agree, initially I renamed the tile "Official releases" but it's wrong since there are also non-official ones (e.g. single cracks or others). So I don't know what title to use. "Non-menu releases" does not sound nice. Do you have any ideas?
>
Perhaps 'Single Disk Releases' (as long as it fits the tile in full screen view). Or we could create a tile with 'offical releases' and 'single disk releases' or something? 

> The text "This game is also found..." I think I tried to put it in a box, but then it would mean a "box in a box" as all the menus would be in that box too and that did not look nice. I tried to change it to put just the text in a box, let me know what you think.
> 
Yes, I agree with you, let's put it back as it was. Again, I really like the different tile look, I though it would look more 'consistent' in 1 tile but I agree with you, it would be difficult to make look good. 

> The missing ℹ️ on the game page: I removed them here to see and I agree it looks nicer. Problem is that there's no way to get to that release currently (except clicking on the menu first, and then on ℹ️). I don't know. Maybe we can just not have menu releases at all? But it would mean we could not document the specifics of that release (such as the trainers options, etc.)
>
I have added my doubts about the release page for menu releases in another threat and will continue this topic over there.

> Responsiveness: I agree a different order would be better. It's hard to achieve though. Let's keep that for last once everything else is sorted out.
>
OK.

**Comment by stgraveyard** [comment]
Nico, for the release box, perhaps you can add an 'i' icon next to the 'Releases' title. When we hoover over it we get a text box saying "official releases and non-official single cracks" or something like this?

**Comment by nguillaumin** [comment]
I wonder if this is actually needed, because we don't include the menu releases in that list... Still, I added it. I also added a little skull & crossbones icon if it's an `Unofficial` release of a `Commercial` software:

![3](https://user-images.githubusercontent.com/762512/109393397-b1467b00-7921-11eb-8c19-bf4d3c031b1a.png)

You can see it here: https://menus.atarilegend.com/games/106

**Comment by stgraveyard** [comment]
Nico I really like it I just wonder why there is not such a cool pop up like you have created for the menu's ?
Really like the skull thing!

**Comment by nguillaumin** [comment]
I just don't want to have to many popups everywhere... But I added one now.

**Comment by stgraveyard** [comment]
If you don't like it, you can remove it. I really do like it, I also think it is cool that is behaves like a link, and that you actually have to click it for the pop up to appear. So once people know what is behind it, they will never click it again. I love it.

**Comment by nguillaumin** [comment]
I think we're happy here too, so closing this.

**Comment by stgraveyard** [comment]
Very happy! ;)
