### ISSUE TITLE
Some information are missing when an AKA name is attached to a game

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#78]
Some information aren't displayed when a game has an AKA name.
Look here:
https://www.atarilegend.com/games/590
Location + publisher aren't displayed.
Thanks & happy new year to the whole team!

![image](https://user-images.githubusercontent.com/12120244/103442769-7eea0b80-4c59-11eb-82b9-c40bab2de5b5.png)

**Comment by nguillaumin** [comment]
Yes, this is intentional as there would not be enough space for everything. We discussed it with STGraveyard at the time and decided to display the release name first, and if there's none then the publisher.

I suggest we keep like that for now since we will review the display of releases anyway?

**Comment by Brume-AL** [comment]
That makes sense, thanks for the reply Nicolas.
I agree: we'll see how we can improve this information with the future display.

**Comment by nguillaumin** [comment]
Ok, closing for now.
