### ISSUE TITLE
Stonish future once the menus are imported in AtariLegend?

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#79]
I'm working on a tool to import Stonish menus into AtariLegend as I assume that's what was intended, however I don't really know :wink: So I wanted to ask @stgraveyard @Brume-AL what was the plan here?

- Was it always intended for all Stonish menus to be imported into AtariLegend?
- Will Stonish still exist after the menus are imported, or should all menus updates / additions be done in AtariLegend?

I'm asking because the import tool I've been writing so far is "single use", i.e. it will import all the Stonish data once but you cannot run it a second time (or it will duplicate everything). It would mean than once the data is imported no more data should be added to Stonish (or it should be manually added in AL as well). We could also investigate building a "sync" tool that could be run regularly but that's a lot more work (especially as the 2 DB don't have the same structure).

**Comment by Brume-AL** [comment]
Yes, we always wanted to import all Stonish menus into AL website. Stonish will be deleted after that.

Let me know when you want to import Stonish db, I'll stop to add menu to the site.

Thanks Nico: that smells really good, one of our dream will come true ;)

**Comment by stgraveyard** [comment]
Stonish is such a nice website and a piece of history, don't you think people will be disappointed if you put it offline @Brume-AL ?

**Comment by Brume-AL** [comment]
Thanks @stgraveyard 😊

But Stonish is a recent website and it's riddled with bugs. My goal has ever been to integrate Stonish into Atari Legend which is the parent of Stonish (do you remember I wanted to try to motivate you to revive Atari Legend 5 or 6 years ago? Mission accomplished 😉).

I guess I'll keep the domain name one or two years in order to redirect each menu to AL, then the site will be closed.

**Comment by nguillaumin** [comment]
If you plan to have redirections, do I need to keep the Stonish menu ID or Stonish crew ID or similar in the AL DB, to make the link? Did you have a think about how to make it work? 🤔

**Comment by MugUK** [comment]
I reckon we do it (if time is not a problem) for April Fool's Day.

We pretend to give up on Stonish and change the page to a big "RIP Stonish" headstone and then announce the new Atari Legend with all the menus on it, the day after or whatever it was for the arising of that hippy from Nazareth :)

**Comment by nguillaumin** [comment]
So it didn't happen on April 1st unfortunately :smile: But I do plan to go live with the menus tomorrow if everything goes well!

@Brume-AL I saw that you have been adding menus to Stonish recently, I will of course import them as I will take the latest version of the Stonish database. Let me know if you have any objection to the go live or if you need a bit more time to upload a few more menus on Stonish before I import them.

**Comment by stgraveyard** [comment]
This is gonna be cool!

**Comment by MugUK** [comment]
Looking forward to this as I can start importing the scrolltexts. 

Some are menu texts (as in scroll upwards) and need 40 char width to be forced. Can I use carriage returns in the scrolltext field in AL so that they stay lined up?

**Comment by nguillaumin** [comment]
Looking forward to this as well! I think once we have a bit more scrolltexts in the database we can add a tile like "random scrolltext" like we did for "random menu", to show them elsewhere on AL.

Good point about the carriage returns, I did not think of that and they were not respected. I have changed it so that you'll be able to use them.

**Comment by nguillaumin** [comment]
Ok, menus are now live! Deployment wasn't fun as I did not realize that the dev & prod site were running on an older version of MySQL, so I had to re-create the databases first and transfer the data... But anyway it's good now. I will delete the test menu site.

**Comment by stgraveyard** [comment]
Lucky we have you on board !! 

Nico, I will make a nice anounce on social media about this. 

But what is this? : 

![image](https://user-images.githubusercontent.com/4339294/114311650-e41e8a00-9aef-11eb-9511-782c108e0216.png)

Also, I need to explain the different cpanels. So the new cpanel is used for menus only so far. Because we also have a menu section in the legacy panel, maybe this needs to be closed down?

**Comment by nguillaumin** [comment]
Yes, could you also add a News item on AL about this?

In the changelog, this is the import script that I ran to import the Stonish data. I wanted to record which crews were changed, but since it was done via a script and not a real user, there was no user to associate with the change.

For CPANEL: Yes, for now only the menu section is on the new CPANEL (There's also the Games > Issue section if you want to take a look). I will remove the menus editor in the Legacy one, it's on my list.

**Comment by Brume-AL** [comment]
That's very great news, thank you a billion time Nicolas for the huge job you made on it! 👍👍👍

I've posted an annoucement on FB, so did Maarten, too.

Thanks again, I was waiting for this moment since we created Atari Legend around 2002-2003!

**Comment by nguillaumin** [comment]
Thanks! It's funny because for me it's also the reason I got in touch with Maarten initially about AL a few years ago, because I wanted to contribute menus to the database but I did not realize it was not ready :wink: So we all finally come full circle!

**Comment by stgraveyard** [comment]
> Thanks! It's funny because for me it's also the reason I got in touch with Maarten initially about AL a few years ago, because I wanted to contribute menus to the database but I did not realize it was not ready 😉 So we all finally come full circle!

Wow wow wow, slow down ... full circle? Please no, there is still a lot of cool stuff to implement and we need you NICO!!!

**Comment by nguillaumin** [comment]
Ahah sure! :laughing:  I just meant on the menus topic!
