### ISSUE TITLE
Menu pages presentation

### ISSUE THREAD

**Issue by nguillaumin** [atari-legend/atari-legend#81]
I've started to work on displaying the menu sets and menus in the main site. Here's what I have so far.

The page displaying all menu sets. I basically copied Stonish as I thought it looked great :smile: . That include the nice little animation when you filter on a specific letter:

![1](https://user-images.githubusercontent.com/762512/104122271-5393aa80-5344-11eb-8c2e-01aef62c7af9.png)

![2](https://user-images.githubusercontent.com/762512/104122273-542c4100-5344-11eb-83a2-0eed062103a8.png)

Note the first menu set "A Clockwork Orange" just for a test I added a second crew. I display the crew only if there are more than one, or if the name of the crew differs from the name of the menu set (which will be infrequent).

Then when you click on a specific set, you get there:

![3](https://user-images.githubusercontent.com/762512/104122274-54c4d780-5344-11eb-830c-2ef45676a6b1.png)

![4](https://user-images.githubusercontent.com/762512/104122275-555d6e00-5344-11eb-886a-ccca7dbb4b9d.png)

There's still polishing needed and the mobile view to work on, but I'd like to know if you think I'm going in the right direction @stgraveyard @Brume-AL @stsilversurfer and others...

Thanks!

**Comment by Brume-AL** [comment]
Again, that's a brilliant work!

The page displaying all menu sets is nice. On the first version of Stonish (long time ago), it displayed the number of menus, too. But I didn't find the good place to display this kind of information on each box. It looked very messy. You managed where I failed 😉

Maybe on the left column could we display latest menus added (similar to the homepage of Stonish)?

**Comment by Brume-AL** [comment]
About the menus page:

I like very much how you display the content of each menu on both columns. That looks very cool 👍👍👍👍👍👍👍

Will you display the menus on different pages? I mean Zuul or Fuzion made more 200 menus. The fullset has to be cut, but you have probably already considered this solution.

**Comment by stgraveyard** [comment]
I think this is so cool it brings a tear to my eye.

When is this comming to dev? I want to start testing and give my remarks! ;)

**Comment by nguillaumin** [comment]
Thanks guys!

Yes I plan to have additional "tiles" showing the latest menus, or a random one, etc. We'll be able to sprinkle these in the site a bit like screenstar, etc.

I thought about pagination indeed, but in the end I'm not sure. At most we'll have 200-300 menus and loading them in one page is actually quite fast. It also makes it simpler if we want to link to a menu from elsewhere if they are in a single page (otherwise we have to calculate which page to display first). So not sure yet...

There's still a fait amount of work before I can put it on dev. The DB structure still needs some work and the Cpanel pages are not finished. I want to wait for the latest moment before merging on the dev branch otherwise it prevents us from making any other changes/fixes without having to deploy the menus as well.

**Comment by nguillaumin** [comment]
Screenshot of displaying a non-game software and the menus it's on:

![boulboot](https://user-images.githubusercontent.com/762512/105634948-d0ed0e00-5e60-11eb-99ed-fce991c949b7.png)

@stgraveyard commented:

> What is Boulboot? And why is boulboot linked to DZ and all the other like 'lablemaker', 'Restart', 'MakeList' ... not? Where are those links leading to? Those are not games, so it seems? And why is there an 'i' behind the games names?

Boulboot is a utility that's part of a menu (indeed as you probably know menus did not only have games). It's linked to DZ because it has a page on Demozoo: https://demozoo.org/productions/95912/ . Labelmaker, Restart and others are indeed non-games, but they don't have a Demozoo page. The links are leading to this exact page, to list all the menu a specific software appears on. It's the same as Stonish:
- The menu page is: http://www.stonish.net/A-Clockwork-Orange-1#st3
- If you click on Boulboot, you get: http://www.stonish.net/search.php?reqsoft=2405
- On that page you can either access other menus, or access Demozoo

The (i) is leading to the release information. The problem is that we need 2 links for each game:
- One link to go to the game page, to see on which other menus the game is present on
- One link to go to the release, with information about the trainers, etc.

That's why I used the (i) for now, but I'm not necessarily happy with it, we can find other ideas.

**Comment by nguillaumin** [comment]
Hi guys, I have deployed the work in progress here: https://menus.atarilegend.com/menusets . Also have a look at changes to game pages to list menus at the bottom, for example: https://menus.atarilegend.com/games/736 .

I added a "random menu" tile, with a screenshot and the content. However I think it would be more interesting to have a "random scrolltext" one (screenshot + scrolltext), that would also be a good incentive to collect more scrolltexts.

The CPANEL part is not complete yet but you can still have a look: https://menus.atarilegend.com/admin/ . The legacy CPANEL is not available for this test site (it's connected to the "wrong" legacy site on `dev.atarilegend.com`, a different database) so you won't be able to make any changes in crews or anything on this test site. It's really mostly for testing the main site, and the specific new CPANEL part.

If you find specific bugs or have specific requests/ideas please open separate issues for each, but for general comments we can keep discussing on this one.

**Comment by nguillaumin** [comment]
Closing this one, since separate tickets are opened for different issues.
