### ISSUE TITLE
Lemon Amiga links

### ISSUE THREAD

**Issue by stsilversurfer** [atari-legend/atari-legend#82]
I got a message from Kim Lemon.

> Hello Sir! 🙂 A new Lemon Amiga website has been launched and the game links now point to: https://www.lemonamiga.com/games/details.php?id=X

**Comment by nguillaumin** [comment]
Changed. Funny because I asked them the same thing when we deployed the new site :smile: https://www.lemonamiga.com/forum/viewtopic.php?f=13&t=17408
