### ISSUE TITLE
Menus main section - Layout

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#84]
![image](https://user-images.githubusercontent.com/4339294/107880157-53f00a00-6edd-11eb-9376-17a0f2c77aed.png)

I love this page, but instead of having an 'A' sign everywhere, why not generate a random image from the menu collection and place it instead? The same size as the 'A'. Or a piece of the image...

**Comment by stgraveyard** [comment]
I love the tile script you used with the flipping tile when switching between letters and wen resizing the screen, can we also implement this in the game search results?

**Comment by nguillaumin** [comment]
I tried it quickly:

![1](https://user-images.githubusercontent.com/762512/107978090-83297880-6fbc-11eb-94fa-7feeb08b14c9.png)

To me it doesn't add a lot of value as the screenshots are too small, and it makes the page actually significantly slower to load. We would have to design the menuset tiles differently and probably make them bigger.

This page is really just an entry point to reach a specific menuset so I don't mind if we keep it simple + it's a bit of a change compared to the rest of the site, which is nice.

Let me know what you think?

**Comment by Brume-AL** [comment]
Hi team,
I've tried to add random screenshots on the Menu Select Page on Stonish some years ago, too. The result was really bad and confusing. I considered to add a filter (some kind of black & white or sepia colors), but the result was not up to my expectations. They're too many styles, too many colors, too many fonts in the menus.
Sorry I'll try to answer some longer messages in the next days. I'm overwhelmed at work but I'll be on vacancy next week.

**Comment by stgraveyard** [comment]
Well, judging from the screenshot, I really like it. I think it looks a lot more playfull, more like the search results in the game section and I don't mind the different styles. I do think we need a filler when there are no screenshots. 
Anyway, AL is becoming more and more your baby, so if you prefer the letter presentation, I will not step in the way ;) 
But for me personally, I would go with this new result page any day, I really like it!

**Comment by nguillaumin** [comment]
Let's keep it with the letters for now. Since we added the progress bars + increased the font size it's already quite busy.
