### ISSUE TITLE
Menudisk detail pages

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#85]
Hi, 

I think there should be some spacing all around the menu disk image 👍 

![image](https://user-images.githubusercontent.com/4339294/107880233-d24cac00-6edd-11eb-9f45-f34d1d3eb1a0.png)

I also think it would be cool to have some kind of pop up info of the different conditions and what they mean (to us) : 

![image](https://user-images.githubusercontent.com/4339294/107880266-088a2b80-6ede-11eb-96d2-3494b38b18ea.png)

Finally, the text of the team should be centered ('Reanimators contains 26 menus and 26 disks.')

Cheers.

**Comment by stgraveyard** [comment]
I love this stuff, this is so nicely presented!

![image](https://user-images.githubusercontent.com/4339294/107880378-a4b43280-6ede-11eb-900d-04fc66c2d5c2.png)

**Comment by stgraveyard** [comment]
I guess this is another conversion issue? 

![image](https://user-images.githubusercontent.com/4339294/107880411-d2997700-6ede-11eb-82f2-a43e82b2dce8.png)

**Comment by stgraveyard** [comment]
AWESOME/ELITE 

Something should be done on the alignment when we have long title : 

![image](https://user-images.githubusercontent.com/4339294/107880439-12f8f500-6edf-11eb-8497-b45fde14785c.png)

**Comment by stgraveyard** [comment]
It would also be nice to be able to add some history about the menudisk team, this is currently missing, I think?

**Comment by nguillaumin** [comment]
I made some changes for the spacing.

For the conditions, I'm happy to add descriptions if someone can provide them. Note that the other conditions are already self-descriptive, so maybe it's just a matter of finding a better word for "Intact"? Stonish had "Safe" but I thought it was not clear enough either:

![2](https://user-images.githubusercontent.com/762512/107982319-1914d180-6fc4-11eb-8305-0c2536508435.png)

For `Georges LefÃ¨vre` it's wrong in the source Stonish DB (I fixed it manually in there so it should be good for the next import)

Long title: Will have a look. It's annoying as it's not easy to fix without explicitly making to separate lists in the code, which in turns has responsiveness impacts...

History about the team: Yes, I think that would be part of the Crew editor (still in old CPANEL). To be considered later I think.

**Comment by stgraveyard** [comment]
> I made some changes for the spacing.
> 
Perfect! 

> For the conditions, I'm happy to add descriptions if someone can provide them. Note that the other conditions are already self-descriptive, so maybe it's just a matter of finding a better word for "Intact"? Stonish had "Safe" but I thought it was not clear enough either:
> 
> ![2](https://user-images.githubusercontent.com/762512/107982319-1914d180-6fc4-11eb-8305-0c2536508435.png)
> 
> For `Georges LefÃ¨vre` it's wrong in the source Stonish DB (I fixed it manually in there so it should be good for the next import)
> 
Great!

> Long title: Will have a look. It's annoying as it's not easy to fix without explicitly making to separate lists in the code, which in turns has responsiveness impacts...
> 
Yes, I understand. In the old version I had the text chop off and add '...' after x nr of letters to fix this. But I know you are not a fan of this method. I just think now it sometimes is a bit 'hard' on the eyes with those blank lines...

> History about the team: Yes, I think that would be part of the Crew editor (still in old CPANEL). To be considered later I think.
>
Aha, I remember I had put this options somewhere. 

Regarding the new CPANEL, I love the no-nonsense white look. Are you converting the complete cpanel to this layout? 

Seriously, I always loved Stonish, but browsing through all these pompey pirates disks, looking at the art, and having our complete database linked to it, seeing all of this in our beautifull AL site...It fills my eyes with nostalgic tears of joy! What an amazing job @nguillaumin ! 

@Brume-AL WE NEED AUTOMATION AND DBUG DISKS ;-)

**Comment by nguillaumin** [comment]
I have fixed the lists, and also reviewed a bit the responsiveness, I think it's much better on small screens now. Have a look?

**Comment by stgraveyard** [comment]
Nico,

It looks much, much better and is just fine for me now. The only think I find weird ... Why is the 'I' at International Championship Athletics not on the same line?

![image](https://user-images.githubusercontent.com/4339294/108625643-54901f80-744c-11eb-8f7c-d59f1055cad2.png)
![image](https://user-images.githubusercontent.com/4339294/108625664-68d41c80-744c-11eb-85e9-ad114e8ea0b7.png)

Responsivenes is ace!

**Comment by nguillaumin** [comment]
Hm, this is an annoying "feature" of HTML it seems. I can either have not skip to the next line, but not have nice spacing between the link and what follows, or the opposite:

![2](https://user-images.githubusercontent.com/762512/108630006-fe7aa680-7462-11eb-8b73-a5391907df53.png)

![3](https://user-images.githubusercontent.com/762512/108630009-ff133d00-7462-11eb-8d50-60b97d95c2ce.png)

So I changed to the latter (not skipping to the next line, but no nice spacing)

**Comment by stgraveyard** [comment]
This is pretty perfect now to me. Thanks!
