### ISSUE TITLE
Copyright not OK on main site

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#87]
Hi Nico, 

On www.atarilegend.com, the footer copyright is not up to date. I I remember correctly, I think I used php to have the current year displayed : 

![image](https://user-images.githubusercontent.com/4339294/108100286-01058680-7086-11eb-8608-24a82fa4be87.png)

Not anymore. Should be an easy fix.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Thanks, fixed. (It will not be on the menus test site)
