### ISSUE TITLE
Game detail - menudisk overview

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#88]
Hi Nico,

When going to the game detail page of the game VROOM, and when you scroll down to the 'game is also on following menudisks' we see this : 

![image](https://user-images.githubusercontent.com/4339294/108107964-3dd67b00-7090-11eb-9b00-bc3c66aecc19.png)

I think for these tiles, on this page, we need to add a limitation to the displayed titles per menu, agreed?

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Done:

![5](https://user-images.githubusercontent.com/762512/108602698-ae88da80-73a3-11eb-932d-dddf4c2188f0.png) ![6](https://user-images.githubusercontent.com/762512/108602699-af217100-73a3-11eb-99e0-02832bf06bf1.png)

**Comment by stgraveyard** [comment]
Wow, absolutely stunning implementation, with the enlarging of the boxes. Great stuff!
