### ISSUE TITLE
Wrong credits given to wrong menu?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#94]
On a page within the Out Of Order menu group, there's a disk that's missing, but has been credited to TheGrey, yet the disk above which does exist hasn't been credited. 

Other donations of this group's menus are from TheGrey, so should the credit on menu 38 really be linked to menu 37?

**Comment by nguillaumin** [comment]
This seems to be an error in the Stonish database. It doesn't show on the Stonish site, but in the database it's wrong:

![1](https://user-images.githubusercontent.com/762512/108415907-5da3a580-722e-11eb-9183-3b51df5a9c96.png)

(110 is the ID of "Out of Order".

@Brume-AL is that something you can fix in Stonish? Then it will get corrected next time I import the data.

**Comment by Brume-AL** [comment]
Sorry for the mistake, it's fixed on Stonish now.

**Comment by MugUK** [comment]
Sorry for spotting these little bugs, but it's my job in real life as well as AL :)

**Comment by nguillaumin** [comment]
Thanks guys. It's good, we all want the DB to be as accurate as possible :+1: 

I have done a re-import so this is correct now.
