### ISSUE TITLE
Possible to have Stonish DB as an Excel file?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#95]
Probably a one-off request, but for me to check on the menu disks when I've got spare time, then I'd prefer to have the Stonish DB in Excel form and then I can go through it quicker and spot the errors.

**Comment by nguillaumin** [comment]
Here's what I can offer with minimal effort:

[menu_disks.zip](https://github.com/atari-legend/atari-legend/files/6015116/menu_disks.zip)

For myself, here's the SQL query:

```sql
SELECT
    *
FROM
    menu_disks
LEFT JOIN menu_disk_dumps ON menu_disks.menu_disk_dump_id = menu_disk_dumps.id
LEFT JOIN menus ON menu_disks.menu_id = menus.id
LEFT JOIN menu_sets ON menus.menu_set_id = menu_sets.id
ORDER BY
    menu_sets.name ASC,
    menus.number ASC,
    menus.issue ASC,
    menu_disks.part ASC
```

Would that be ok?

**Comment by MugUK** [comment]
Almost perfect. But the scrolltext buggers it up because some of them are so long.

Can I have it with the scrolltext?

**Comment by nguillaumin** [comment]
For me I can open it as-is in LibreOffice, so I just removed the column:

[menu_disks_no_scrolls.zip](https://github.com/atari-legend/atari-legend/files/6015423/menu_disks_no_scrolls.zip)

**Comment by MugUK** [comment]
Cheers. It will help me as I extract the scrolltexts / check the contents etc.

**Comment by MugUK** [comment]
First mistake. Don't realign the columns after import as then you find that some of the Notes use carriage lines in them. Which Excel hates with a passion and tries to move all the data after Notes onto a new line.

Attempt #3 later on today to get a fully working list :)
