### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs1409211.users' doesn't exist (SQL: select * from `users` where `last_visit` >= 1613828877) 

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#96]
Just clicked on the random menu section and got the above error:

"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs1409211.users' doesn't exist (SQL: select * from `users` where `last_visit` >= 1613828877)" 

Is there something wrong or is a fresh import happening and it's just bad timing on my part?

**Comment by MugUK** [comment]
OK, must have been a temporary issue as it's working now.

**Comment by nguillaumin** [comment]
Yes, I'm doing a re-import right now :wink:  should be completed in a few minutes.
