### ISSUE TITLE
Can't click on A-Z links from T afterwards as no menus show up

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#97]
As the latest Stonish DB has just been imported, this might be linked. 

On Stonish there are menus for letters T through to Z (except V) but on the current AL database, nothing appears when you click on any letter after S on the alphabetical row at the top of the menus screen.

**Comment by nguillaumin** [comment]
I thin the import was still going, it works now.

**Comment by MugUK** [comment]
Phew! 

Maybe we need to create a fake crew that starts with the letter V :)

**Comment by Brume-AL** [comment]
> 
> 
> Phew!
> 
> Maybe we need to create a fake crew that starts with the letter V :)

😄😄😄

I suggest Vatari Vegend. Members are VugUK, VynXX, Vrume, VtGraveyard, Vilfer Vurfer, Varcer...

**Comment by MugUK** [comment]
Pity Vulcan didn't want to create his own crew as on the random Out Of Order 42 menu. Everything bar the crack of Indiana Jones was by Vulcan. Breathing in and out by Vulcan. Buying the groceries .. by Vulcan etc. etc.
