### ISSUE TITLE
Scrolltexts from -all- menus?

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#98]
As I spotted in the first export of the Stonish DB - some of the menus have their scrollers included.

Are we going to be including that in the menus as some kind of pop-up window? If so, then I can start ripping the scroll texts out group by group.

Would the countless amount of swearwords in some menus mark us down in search engines? Or can we hide that field?

**Comment by stgraveyard** [comment]
Hi Mike,

The scrolltexts from Stonish are implemented in a very nifty way IMO : 

![image](https://user-images.githubusercontent.com/4339294/108599611-7d53de80-7392-11eb-88ae-757d9cf17a75.png)

Would be amazing to have all the scrolltexts in there just for history preservation.

**Comment by nguillaumin** [comment]
Indeed, scrolltexts are "hidden" by default, but maybe clicking on the little scroll icon is not obvious enough, if Mike did not find it?

Search-engine wise, only way to hide then would be top open in a popup which I think would not be nice. I say for now let's include as much as we can, if it affect our ranking negatively we'll cross that bridge when we come to it.

Out of curiosity how do you rip them? Myself I run in Hatari, make a dump of the RAM and search for strings inside. Is there a faster / better way?

**Comment by MugUK** [comment]
Ah because there were so few to see, I didn't spot the icon. My bad. 

Maybe, if it can fit, can we put TXT in pixels into the icon?

The majority of menus are all file-based, so I could copy all of the .PRG from the one group's disks into an emulated hard-disk folder under STEEM / Hatari. Then use NewDepack to unpack them all. 

Only a few menu disks would be protected using an encryption routine like Cameo 0.5/0.6, so you run them through Dec0de by Orion/Replicants and then depack.

Once you have them all depacked, you can open them in Notepad++ (or whatever is your choice of text editors) if necessary and 90% of the menu texts will be there to copy & paste elsewhere.

**Comment by MugUK** [comment]
Is it possible to have a TAR of every single menu, or just a page where I can use my file extension DownThemAll so that I can grab them in one file or just a page of links for 1 x ZIP per group?

**Comment by MugUK** [comment]
I'll then need to do a batch MSA->ST so that I can put them on my Gotek to make it easier.

**Comment by Brume-AL** [comment]
Thanks for your offer Mike.
Here an archive of the menus stored on the site:
http://stonish.net/download/mike.7z

**Comment by Brume-AL** [comment]
Btw, no need to work on Fuzion scrolltexts since Orion alredy ripped them. I started to upload them on the site long time ago, but I forgot to finalize the job. Will do it asap.
They are on demozoo, too.

**Comment by nguillaumin** [comment]
Thanks guys, having more scrolltexts would be awesome!

For the icon I can't put TXT inside (and it would probably be too small), so I did this:

![1](https://user-images.githubusercontent.com/762512/108621265-feae7e00-7431-11eb-97d0-88e7f142a825.png)

Let me know what you think?

**Comment by MugUK** [comment]
Scroll and Text - even I can work that out :)

**Comment by MugUK** [comment]
> 
> 
> Btw, no need to work on Fuzion scrolltexts since Orion alredy ripped them. I started to upload them on the site long time ago, but I forgot to finalize the job. Will do it asap.
> They are on demozoo, too.

So those that are on DemoZoo we can upload there as well? I'll keep a separate text file extract for each menu then.

**Comment by Brume-AL** [comment]
Yes, Orion sent them to me, too. We can upload them on Atari Legend, too.

**Comment by Brume-AL** [comment]
> 
> 
> Thanks guys, having more scrolltexts would be awesome!
> 
> For the icon I can't put TXT inside (and it would probably be too small), so I did this:
> 
> ![1](https://user-images.githubusercontent.com/762512/108621265-feae7e00-7431-11eb-97d0-88e7f142a825.png)
> 
> Let me know what you think?

Looks fine to me 👍👍👍

**Comment by MugUK** [comment]
So where there's an "anti-hacker" message embedded in the menu. Do we extract that as well?

E.g. ACE 5 has the scrolltext as well as a "get in touch if you think you're good enough" with a proper phone number.

**Comment by MugUK** [comment]
I'm assuming that we will also mask out full addresses and phone numbers if they're listed?

**Comment by nguillaumin** [comment]
For me "anti hacker" message is overkill. Currently there's no spot in the DB to store it. But if a majority wants it, we can add it.

Masking addresses & phone numbers: I think it would be difficult to do well automatically, since they could be in a lot of different formats. The vast majority of them are probably obsolete, no? So I would say we keep them as-is. Alternatively when putting the scrolltexts in the DB in CPANEL, manually remove them.

**Comment by MugUK** [comment]
OK, I'll leave them in for now as you say, most are between 25-30 years out of date. Although my contact address from the days of old is still valid as my folks still live there :)

**Comment by MugUK** [comment]
I've done 25 folders of groups. I started with those that I hadn't heard of before as well as some folders with only 1 or 2 menus in it.

When I've got a lot ready, do I just ZIP them all up and let you know where to find them Brume?

**Comment by MugUK** [comment]
First batch sent to Brume to look at. Also includes a batch of menus without scrolltexts too.

**Comment by nguillaumin** [comment]
Awesome, looking forward to it!!

Closing this since there's nothing else to do on the AL side.
