### ISSUE TITLE
Mad Vision menus don't need [no number] as they used letters for their menus

### ISSUE THREAD

**Issue by MugUK** [atari-legend/atari-legend#99]
https://menus.atarilegend.com/menusets/120?page=1 etc.

Only the first two entries, the ones without a menu, are properly shown as they don't have any numbers.

For all the other menus it was:
Menu A, B, C etc. 

and not:
Menu # [no number] A

(Same for any other group that did menus with letters not numbers)

**Comment by nguillaumin** [comment]
Thanks, should be fixed now.
